/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsUser implements Serializable {

    private static final long serialVersionUID = -258034194;

    private Long    id;
    private Long    roleId;
    private Long    fieldId;
    private String  account;
    private String  name;
    private String  password;
    private Boolean gender;
    private String  mail;
    private String  company;
    private Long    phone;
    private Long    qq;
    private String  status;
    private String  remark;

    public CloudinsUser() {}

    public CloudinsUser(CloudinsUser value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.fieldId = value.fieldId;
        this.account = value.account;
        this.name = value.name;
        this.password = value.password;
        this.gender = value.gender;
        this.mail = value.mail;
        this.company = value.company;
        this.phone = value.phone;
        this.qq = value.qq;
        this.status = value.status;
        this.remark = value.remark;
    }

    public CloudinsUser(
        Long    id,
        Long    roleId,
        Long    fieldId,
        String  account,
        String  name,
        String  password,
        Boolean gender,
        String  mail,
        String  company,
        Long    phone,
        Long    qq,
        String  status,
        String  remark
    ) {
        this.id = id;
        this.roleId = roleId;
        this.fieldId = fieldId;
        this.account = account;
        this.name = name;
        this.password = password;
        this.gender = gender;
        this.mail = mail;
        this.company = company;
        this.phone = phone;
        this.qq = qq;
        this.status = status;
        this.remark = remark;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getFieldId() {
        return this.fieldId;
    }

    public void setFieldId(Long fieldId) {
        this.fieldId = fieldId;
    }

    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getGender() {
        return this.gender;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public Long getPhone() {
        return this.phone;
    }

    public void setPhone(Long phone) {
        this.phone = phone;
    }

    public Long getQq() {
        return this.qq;
    }

    public void setQq(Long qq) {
        this.qq = qq;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CloudinsUser (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(fieldId);
        sb.append(", ").append(account);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(gender);
        sb.append(", ").append(mail);
        sb.append(", ").append(company);
        sb.append(", ").append(phone);
        sb.append(", ").append(qq);
        sb.append(", ").append(status);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
