/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsField implements Serializable {

    private static final long serialVersionUID = 336680090;

    private Long   id;
    private String name;
    private Long   managerId;
    private String managerName;
    private String hostIp;
    private String hostUsername;
    private String hostPassword;
    private String company;
    private String remark;

    public CloudinsField() {}

    public CloudinsField(CloudinsField value) {
        this.id = value.id;
        this.name = value.name;
        this.managerId = value.managerId;
        this.managerName = value.managerName;
        this.hostIp = value.hostIp;
        this.hostUsername = value.hostUsername;
        this.hostPassword = value.hostPassword;
        this.company = value.company;
        this.remark = value.remark;
    }

    public CloudinsField(
        Long   id,
        String name,
        Long   managerId,
        String managerName,
        String hostIp,
        String hostUsername,
        String hostPassword,
        String company,
        String remark
    ) {
        this.id = id;
        this.name = name;
        this.managerId = managerId;
        this.managerName = managerName;
        this.hostIp = hostIp;
        this.hostUsername = hostUsername;
        this.hostPassword = hostPassword;
        this.company = company;
        this.remark = remark;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getManagerId() {
        return this.managerId;
    }

    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    public String getManagerName() {
        return this.managerName;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    public String getHostIp() {
        return this.hostIp;
    }

    public void setHostIp(String hostIp) {
        this.hostIp = hostIp;
    }

    public String getHostUsername() {
        return this.hostUsername;
    }

    public void setHostUsername(String hostUsername) {
        this.hostUsername = hostUsername;
    }

    public String getHostPassword() {
        return this.hostPassword;
    }

    public void setHostPassword(String hostPassword) {
        this.hostPassword = hostPassword;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CloudinsFieldTable (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(managerId);
        sb.append(", ").append(managerName);
        sb.append(", ").append(hostIp);
        sb.append(", ").append(hostUsername);
        sb.append(", ").append(hostPassword);
        sb.append(", ").append(company);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
