/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsLog implements Serializable {

    private static final long serialVersionUID = -817989718;

    private Long    id;
    private String  level;
    private String  method;
    private String  message;
    private Long    time;
    private Integer line;
    private Boolean displayed;
    private Boolean read;

    public CloudinsLog() {}

    public CloudinsLog(CloudinsLog value) {
        this.id = value.id;
        this.level = value.level;
        this.method = value.method;
        this.message = value.message;
        this.time = value.time;
        this.line = value.line;
        this.displayed = value.displayed;
        this.read = value.read;
    }

    public CloudinsLog(
        Long    id,
        String  level,
        String  method,
        String  message,
        Long    time,
        Integer line,
        Boolean displayed,
        Boolean read
    ) {
        this.id = id;
        this.level = level;
        this.method = method;
        this.message = message;
        this.time = time;
        this.line = line;
        this.displayed = displayed;
        this.read = read;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getTime() {
        return this.time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getLine() {
        return this.line;
    }

    public void setLine(Integer line) {
        this.line = line;
    }

    public Boolean getDisplayed() {
        return this.displayed;
    }

    public void setDisplayed(Boolean displayed) {
        this.displayed = displayed;
    }

    public Boolean getRead() {
        return this.read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CloudinsLog (");

        sb.append(id);
        sb.append(", ").append(level);
        sb.append(", ").append(method);
        sb.append(", ").append(message);
        sb.append(", ").append(time);
        sb.append(", ").append(line);
        sb.append(", ").append(displayed);
        sb.append(", ").append(read);

        sb.append(")");
        return sb.toString();
    }
}
