/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsField implements Serializable {

    private static final long serialVersionUID = 713835153;

    private Integer id;
    private String  name;
    private String  hostIp;
    private String  hostUsername;
    private String  hostPassword;
    private String  remark;

    public CloudinsField() {}

    public CloudinsField(CloudinsField value) {
        this.id = value.id;
        this.name = value.name;
        this.hostIp = value.hostIp;
        this.hostUsername = value.hostUsername;
        this.hostPassword = value.hostPassword;
        this.remark = value.remark;
    }

    public CloudinsField(
        Integer id,
        String  name,
        String  hostIp,
        String  hostUsername,
        String  hostPassword,
        String  remark
    ) {
        this.id = id;
        this.name = name;
        this.hostIp = hostIp;
        this.hostUsername = hostUsername;
        this.hostPassword = hostPassword;
        this.remark = remark;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getHostIp() {
        return this.hostIp;
    }

    public void setHostIp(String hostIp) {
        this.hostIp = hostIp;
    }

    public String getHostUsername() {
        return this.hostUsername;
    }

    public void setHostUsername(String hostUsername) {
        this.hostUsername = hostUsername;
    }

    public String getHostPassword() {
        return this.hostPassword;
    }

    public void setHostPassword(String hostPassword) {
        this.hostPassword = hostPassword;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CloudinsField (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(hostIp);
        sb.append(", ").append(hostUsername);
        sb.append(", ").append(hostPassword);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
