/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsSpanBaseline implements Serializable {

    private static final long serialVersionUID = -1159062920;

    private Long   traceId;
    private Long   id;
    private String traceMd5;
    private String name;
    private Long   parentId;
    private Long   startTs;
    private Long   duration;

    public CloudinsSpanBaseline() {}

    public CloudinsSpanBaseline(CloudinsSpanBaseline value) {
        this.traceId = value.traceId;
        this.id = value.id;
        this.traceMd5 = value.traceMd5;
        this.name = value.name;
        this.parentId = value.parentId;
        this.startTs = value.startTs;
        this.duration = value.duration;
    }

    public CloudinsSpanBaseline(
        Long   traceId,
        Long   id,
        String traceMd5,
        String name,
        Long   parentId,
        Long   startTs,
        Long   duration
    ) {
        this.traceId = traceId;
        this.id = id;
        this.traceMd5 = traceMd5;
        this.name = name;
        this.parentId = parentId;
        this.startTs = startTs;
        this.duration = duration;
    }

    public Long getTraceId() {
        return this.traceId;
    }

    public void setTraceId(Long traceId) {
        this.traceId = traceId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTraceMd5() {
        return this.traceMd5;
    }

    public void setTraceMd5(String traceMd5) {
        this.traceMd5 = traceMd5;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getStartTs() {
        return this.startTs;
    }

    public void setStartTs(Long startTs) {
        this.startTs = startTs;
    }

    public Long getDuration() {
        return this.duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CloudinsSpanBaseline (");

        sb.append(traceId);
        sb.append(", ").append(id);
        sb.append(", ").append(traceMd5);
        sb.append(", ").append(name);
        sb.append(", ").append(parentId);
        sb.append(", ").append(startTs);
        sb.append(", ").append(duration);

        sb.append(")");
        return sb.toString();
    }
}
