/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsUser implements Serializable {

    private static final long serialVersionUID = 649797047;

    private Integer id;
    private Integer roleId;
    private String  fieldId;
    private String  name;
    private String  password;
    private String  mail;
    private String  status;
    private String  remark;

    public CloudinsUser() {}

    public CloudinsUser(CloudinsUser value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.fieldId = value.fieldId;
        this.name = value.name;
        this.password = value.password;
        this.mail = value.mail;
        this.status = value.status;
        this.remark = value.remark;
    }

    public CloudinsUser(
        Integer id,
        Integer roleId,
        String  fieldId,
        String  name,
        String  password,
        String  mail,
        String  status,
        String  remark
    ) {
        this.id = id;
        this.roleId = roleId;
        this.fieldId = fieldId;
        this.name = name;
        this.password = password;
        this.mail = mail;
        this.status = status;
        this.remark = remark;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getFieldId() {
        return this.fieldId;
    }

    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CloudinsUser (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(fieldId);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(mail);
        sb.append(", ").append(status);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
