/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoricalPeak implements Serializable {

    private static final long serialVersionUID = -646772366;

    private Integer id;
    private String  summaryDate;
    private String  startTime;
    private String  endTime;
    private String  triggerJobNum;
    private String  endJobNum;

    public HistoricalPeak() {}

    public HistoricalPeak(HistoricalPeak value) {
        this.id = value.id;
        this.summaryDate = value.summaryDate;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.triggerJobNum = value.triggerJobNum;
        this.endJobNum = value.endJobNum;
    }

    public HistoricalPeak(
        Integer id,
        String  summaryDate,
        String  startTime,
        String  endTime,
        String  triggerJobNum,
        String  endJobNum
    ) {
        this.id = id;
        this.summaryDate = summaryDate;
        this.startTime = startTime;
        this.endTime = endTime;
        this.triggerJobNum = triggerJobNum;
        this.endJobNum = endJobNum;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSummaryDate() {
        return this.summaryDate;
    }

    public void setSummaryDate(String summaryDate) {
        this.summaryDate = summaryDate;
    }

    public String getStartTime() {
        return this.startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return this.endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getTriggerJobNum() {
        return this.triggerJobNum;
    }

    public void setTriggerJobNum(String triggerJobNum) {
        this.triggerJobNum = triggerJobNum;
    }

    public String getEndJobNum() {
        return this.endJobNum;
    }

    public void setEndJobNum(String endJobNum) {
        this.endJobNum = endJobNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HistoricalPeak (");

        sb.append(id);
        sb.append(", ").append(summaryDate);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(triggerJobNum);
        sb.append(", ").append(endJobNum);

        sb.append(")");
        return sb.toString();
    }
}
