/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobSummaryBasic implements Serializable {

    private static final long serialVersionUID = -364664271;

    private Integer id;
    private String  summaryDate;
    private String  startTime;
    private String  lastUpdateTime;
    private String  jobTotalNum;
    private String  jobCriticalNum;
    private String  jobSevereNum;
    private String  jobModerateNum;
    private String  jobNormalNum;
    private String  jobTypeNum;
    private String  userNum;

    public JobSummaryBasic() {}

    public JobSummaryBasic(JobSummaryBasic value) {
        this.id = value.id;
        this.summaryDate = value.summaryDate;
        this.startTime = value.startTime;
        this.lastUpdateTime = value.lastUpdateTime;
        this.jobTotalNum = value.jobTotalNum;
        this.jobCriticalNum = value.jobCriticalNum;
        this.jobSevereNum = value.jobSevereNum;
        this.jobModerateNum = value.jobModerateNum;
        this.jobNormalNum = value.jobNormalNum;
        this.jobTypeNum = value.jobTypeNum;
        this.userNum = value.userNum;
    }

    public JobSummaryBasic(
        Integer id,
        String  summaryDate,
        String  startTime,
        String  lastUpdateTime,
        String  jobTotalNum,
        String  jobCriticalNum,
        String  jobSevereNum,
        String  jobModerateNum,
        String  jobNormalNum,
        String  jobTypeNum,
        String  userNum
    ) {
        this.id = id;
        this.summaryDate = summaryDate;
        this.startTime = startTime;
        this.lastUpdateTime = lastUpdateTime;
        this.jobTotalNum = jobTotalNum;
        this.jobCriticalNum = jobCriticalNum;
        this.jobSevereNum = jobSevereNum;
        this.jobModerateNum = jobModerateNum;
        this.jobNormalNum = jobNormalNum;
        this.jobTypeNum = jobTypeNum;
        this.userNum = userNum;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSummaryDate() {
        return this.summaryDate;
    }

    public void setSummaryDate(String summaryDate) {
        this.summaryDate = summaryDate;
    }

    public String getStartTime() {
        return this.startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public String getJobTotalNum() {
        return this.jobTotalNum;
    }

    public void setJobTotalNum(String jobTotalNum) {
        this.jobTotalNum = jobTotalNum;
    }

    public String getJobCriticalNum() {
        return this.jobCriticalNum;
    }

    public void setJobCriticalNum(String jobCriticalNum) {
        this.jobCriticalNum = jobCriticalNum;
    }

    public String getJobSevereNum() {
        return this.jobSevereNum;
    }

    public void setJobSevereNum(String jobSevereNum) {
        this.jobSevereNum = jobSevereNum;
    }

    public String getJobModerateNum() {
        return this.jobModerateNum;
    }

    public void setJobModerateNum(String jobModerateNum) {
        this.jobModerateNum = jobModerateNum;
    }

    public String getJobNormalNum() {
        return this.jobNormalNum;
    }

    public void setJobNormalNum(String jobNormalNum) {
        this.jobNormalNum = jobNormalNum;
    }

    public String getJobTypeNum() {
        return this.jobTypeNum;
    }

    public void setJobTypeNum(String jobTypeNum) {
        this.jobTypeNum = jobTypeNum;
    }

    public String getUserNum() {
        return this.userNum;
    }

    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JobSummaryBasic (");

        sb.append(id);
        sb.append(", ").append(summaryDate);
        sb.append(", ").append(startTime);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(jobTotalNum);
        sb.append(", ").append(jobCriticalNum);
        sb.append(", ").append(jobSevereNum);
        sb.append(", ").append(jobModerateNum);
        sb.append(", ").append(jobNormalNum);
        sb.append(", ").append(jobTypeNum);
        sb.append(", ").append(userNum);

        sb.append(")");
        return sb.toString();
    }
}
