/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobTypeSummary implements Serializable {

    private static final long serialVersionUID = -1757925743;

    private Integer id;
    private Integer jobSummaryBasicId;
    private String  jobTypeName;
    private String  jobTypeNum;
    private String  jobTotalNum;
    private String  jobCriticalNum;
    private String  jobSevereNum;
    private String  jobModerateNum;
    private String  jobNormalNum;

    public JobTypeSummary() {}

    public JobTypeSummary(JobTypeSummary value) {
        this.id = value.id;
        this.jobSummaryBasicId = value.jobSummaryBasicId;
        this.jobTypeName = value.jobTypeName;
        this.jobTypeNum = value.jobTypeNum;
        this.jobTotalNum = value.jobTotalNum;
        this.jobCriticalNum = value.jobCriticalNum;
        this.jobSevereNum = value.jobSevereNum;
        this.jobModerateNum = value.jobModerateNum;
        this.jobNormalNum = value.jobNormalNum;
    }

    public JobTypeSummary(
        Integer id,
        Integer jobSummaryBasicId,
        String  jobTypeName,
        String  jobTypeNum,
        String  jobTotalNum,
        String  jobCriticalNum,
        String  jobSevereNum,
        String  jobModerateNum,
        String  jobNormalNum
    ) {
        this.id = id;
        this.jobSummaryBasicId = jobSummaryBasicId;
        this.jobTypeName = jobTypeName;
        this.jobTypeNum = jobTypeNum;
        this.jobTotalNum = jobTotalNum;
        this.jobCriticalNum = jobCriticalNum;
        this.jobSevereNum = jobSevereNum;
        this.jobModerateNum = jobModerateNum;
        this.jobNormalNum = jobNormalNum;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getJobSummaryBasicId() {
        return this.jobSummaryBasicId;
    }

    public void setJobSummaryBasicId(Integer jobSummaryBasicId) {
        this.jobSummaryBasicId = jobSummaryBasicId;
    }

    public String getJobTypeName() {
        return this.jobTypeName;
    }

    public void setJobTypeName(String jobTypeName) {
        this.jobTypeName = jobTypeName;
    }

    public String getJobTypeNum() {
        return this.jobTypeNum;
    }

    public void setJobTypeNum(String jobTypeNum) {
        this.jobTypeNum = jobTypeNum;
    }

    public String getJobTotalNum() {
        return this.jobTotalNum;
    }

    public void setJobTotalNum(String jobTotalNum) {
        this.jobTotalNum = jobTotalNum;
    }

    public String getJobCriticalNum() {
        return this.jobCriticalNum;
    }

    public void setJobCriticalNum(String jobCriticalNum) {
        this.jobCriticalNum = jobCriticalNum;
    }

    public String getJobSevereNum() {
        return this.jobSevereNum;
    }

    public void setJobSevereNum(String jobSevereNum) {
        this.jobSevereNum = jobSevereNum;
    }

    public String getJobModerateNum() {
        return this.jobModerateNum;
    }

    public void setJobModerateNum(String jobModerateNum) {
        this.jobModerateNum = jobModerateNum;
    }

    public String getJobNormalNum() {
        return this.jobNormalNum;
    }

    public void setJobNormalNum(String jobNormalNum) {
        this.jobNormalNum = jobNormalNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JobTypeSummary (");

        sb.append(id);
        sb.append(", ").append(jobSummaryBasicId);
        sb.append(", ").append(jobTypeName);
        sb.append(", ").append(jobTypeNum);
        sb.append(", ").append(jobTotalNum);
        sb.append(", ").append(jobCriticalNum);
        sb.append(", ").append(jobSevereNum);
        sb.append(", ").append(jobModerateNum);
        sb.append(", ").append(jobNormalNum);

        sb.append(")");
        return sb.toString();
    }
}
