/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayEvolutions implements Serializable {

    private static final long serialVersionUID = 1296115148;

    private Integer   id;
    private String    hash;
    private Timestamp appliedAt;
    private String    applyScript;
    private String    revertScript;
    private String    state;
    private String    lastProblem;

    public PlayEvolutions() {}

    public PlayEvolutions(PlayEvolutions value) {
        this.id = value.id;
        this.hash = value.hash;
        this.appliedAt = value.appliedAt;
        this.applyScript = value.applyScript;
        this.revertScript = value.revertScript;
        this.state = value.state;
        this.lastProblem = value.lastProblem;
    }

    public PlayEvolutions(
        Integer   id,
        String    hash,
        Timestamp appliedAt,
        String    applyScript,
        String    revertScript,
        String    state,
        String    lastProblem
    ) {
        this.id = id;
        this.hash = hash;
        this.appliedAt = appliedAt;
        this.applyScript = applyScript;
        this.revertScript = revertScript;
        this.state = state;
        this.lastProblem = lastProblem;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public Timestamp getAppliedAt() {
        return this.appliedAt;
    }

    public void setAppliedAt(Timestamp appliedAt) {
        this.appliedAt = appliedAt;
    }

    public String getApplyScript() {
        return this.applyScript;
    }

    public void setApplyScript(String applyScript) {
        this.applyScript = applyScript;
    }

    public String getRevertScript() {
        return this.revertScript;
    }

    public void setRevertScript(String revertScript) {
        this.revertScript = revertScript;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getLastProblem() {
        return this.lastProblem;
    }

    public void setLastProblem(String lastProblem) {
        this.lastProblem = lastProblem;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayEvolutions (");

        sb.append(id);
        sb.append(", ").append(hash);
        sb.append(", ").append(appliedAt);
        sb.append(", ").append(applyScript);
        sb.append(", ").append(revertScript);
        sb.append(", ").append(state);
        sb.append(", ").append(lastProblem);

        sb.append(")");
        return sb.toString();
    }
}
