/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpanInfos implements Serializable {

    private static final long serialVersionUID = 1549566802;

    private String name;
    private String alias;
    private String defBaseline;
    private String custBaseline;

    public SpanInfos() {}

    public SpanInfos(SpanInfos value) {
        this.name = value.name;
        this.alias = value.alias;
        this.defBaseline = value.defBaseline;
        this.custBaseline = value.custBaseline;
    }

    public SpanInfos(
        String name,
        String alias,
        String defBaseline,
        String custBaseline
    ) {
        this.name = name;
        this.alias = alias;
        this.defBaseline = defBaseline;
        this.custBaseline = custBaseline;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getDefBaseline() {
        return this.defBaseline;
    }

    public void setDefBaseline(String defBaseline) {
        this.defBaseline = defBaseline;
    }

    public String getCustBaseline() {
        return this.custBaseline;
    }

    public void setCustBaseline(String custBaseline) {
        this.custBaseline = custBaseline;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SpanInfos (");

        sb.append(name);
        sb.append(", ").append(alias);
        sb.append(", ").append(defBaseline);
        sb.append(", ").append(custBaseline);

        sb.append(")");
        return sb.toString();
    }
}
