/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Traces implements Serializable {

    private static final long serialVersionUID = 626831479;

    private Long   traceId;
    private String traceMd5;
    private Long   startTs;
    private Long   recordTs;
    private Long   duration;
    private Long   endTs;
    private Short  teamCode;

    public Traces() {}

    public Traces(Traces value) {
        this.traceId = value.traceId;
        this.traceMd5 = value.traceMd5;
        this.startTs = value.startTs;
        this.recordTs = value.recordTs;
        this.duration = value.duration;
        this.endTs = value.endTs;
        this.teamCode = value.teamCode;
    }

    public Traces(
        Long   traceId,
        String traceMd5,
        Long   startTs,
        Long   recordTs,
        Long   duration,
        Long   endTs,
        Short  teamCode
    ) {
        this.traceId = traceId;
        this.traceMd5 = traceMd5;
        this.startTs = startTs;
        this.recordTs = recordTs;
        this.duration = duration;
        this.endTs = endTs;
        this.teamCode = teamCode;
    }

    public Long getTraceId() {
        return this.traceId;
    }

    public void setTraceId(Long traceId) {
        this.traceId = traceId;
    }

    public String getTraceMd5() {
        return this.traceMd5;
    }

    public void setTraceMd5(String traceMd5) {
        this.traceMd5 = traceMd5;
    }

    public Long getStartTs() {
        return this.startTs;
    }

    public void setStartTs(Long startTs) {
        this.startTs = startTs;
    }

    public Long getRecordTs() {
        return this.recordTs;
    }

    public void setRecordTs(Long recordTs) {
        this.recordTs = recordTs;
    }

    public Long getDuration() {
        return this.duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Long getEndTs() {
        return this.endTs;
    }

    public void setEndTs(Long endTs) {
        this.endTs = endTs;
    }

    public Short getTeamCode() {
        return this.teamCode;
    }

    public void setTeamCode(Short teamCode) {
        this.teamCode = teamCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Traces (");

        sb.append(traceId);
        sb.append(", ").append(traceMd5);
        sb.append(", ").append(startTs);
        sb.append(", ").append(recordTs);
        sb.append(", ").append(duration);
        sb.append(", ").append(endTs);
        sb.append(", ").append(teamCode);

        sb.append(")");
        return sb.toString();
    }
}
