/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppResult implements Serializable {

    private static final long serialVersionUID = 546078445;

    private String   id;
    private String   name;
    private String   username;
    private String   queueName;
    private ULong    startTime;
    private ULong    finishTime;
    private Long     recordTs;
    private String   trackingUrl;
    private String   jobType;
    private Boolean  severity;
    private UInteger score;
    private Boolean  workflowDepth;
    private String   scheduler;
    private String   jobName;
    private String   jobExecId;
    private String   flowExecId;
    private String   jobDefId;
    private String   flowDefId;
    private String   jobExecUrl;
    private String   flowExecUrl;
    private String   jobDefUrl;
    private String   flowDefUrl;

    public YarnAppResult() {}

    public YarnAppResult(YarnAppResult value) {
        this.id = value.id;
        this.name = value.name;
        this.username = value.username;
        this.queueName = value.queueName;
        this.startTime = value.startTime;
        this.finishTime = value.finishTime;
        this.recordTs = value.recordTs;
        this.trackingUrl = value.trackingUrl;
        this.jobType = value.jobType;
        this.severity = value.severity;
        this.score = value.score;
        this.workflowDepth = value.workflowDepth;
        this.scheduler = value.scheduler;
        this.jobName = value.jobName;
        this.jobExecId = value.jobExecId;
        this.flowExecId = value.flowExecId;
        this.jobDefId = value.jobDefId;
        this.flowDefId = value.flowDefId;
        this.jobExecUrl = value.jobExecUrl;
        this.flowExecUrl = value.flowExecUrl;
        this.jobDefUrl = value.jobDefUrl;
        this.flowDefUrl = value.flowDefUrl;
    }

    public YarnAppResult(
        String   id,
        String   name,
        String   username,
        String   queueName,
        ULong    startTime,
        ULong    finishTime,
        Long     recordTs,
        String   trackingUrl,
        String   jobType,
        Boolean  severity,
        UInteger score,
        Boolean  workflowDepth,
        String   scheduler,
        String   jobName,
        String   jobExecId,
        String   flowExecId,
        String   jobDefId,
        String   flowDefId,
        String   jobExecUrl,
        String   flowExecUrl,
        String   jobDefUrl,
        String   flowDefUrl
    ) {
        this.id = id;
        this.name = name;
        this.username = username;
        this.queueName = queueName;
        this.startTime = startTime;
        this.finishTime = finishTime;
        this.recordTs = recordTs;
        this.trackingUrl = trackingUrl;
        this.jobType = jobType;
        this.severity = severity;
        this.score = score;
        this.workflowDepth = workflowDepth;
        this.scheduler = scheduler;
        this.jobName = jobName;
        this.jobExecId = jobExecId;
        this.flowExecId = flowExecId;
        this.jobDefId = jobDefId;
        this.flowDefId = flowDefId;
        this.jobExecUrl = jobExecUrl;
        this.flowExecUrl = flowExecUrl;
        this.jobDefUrl = jobDefUrl;
        this.flowDefUrl = flowDefUrl;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getQueueName() {
        return this.queueName;
    }

    public void setQueueName(String queueName) {
        this.queueName = queueName;
    }

    public ULong getStartTime() {
        return this.startTime;
    }

    public void setStartTime(ULong startTime) {
        this.startTime = startTime;
    }

    public ULong getFinishTime() {
        return this.finishTime;
    }

    public void setFinishTime(ULong finishTime) {
        this.finishTime = finishTime;
    }

    public Long getRecordTs() {
        return this.recordTs;
    }

    public void setRecordTs(Long recordTs) {
        this.recordTs = recordTs;
    }

    public String getTrackingUrl() {
        return this.trackingUrl;
    }

    public void setTrackingUrl(String trackingUrl) {
        this.trackingUrl = trackingUrl;
    }

    public String getJobType() {
        return this.jobType;
    }

    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    public Boolean getSeverity() {
        return this.severity;
    }

    public void setSeverity(Boolean severity) {
        this.severity = severity;
    }

    public UInteger getScore() {
        return this.score;
    }

    public void setScore(UInteger score) {
        this.score = score;
    }

    public Boolean getWorkflowDepth() {
        return this.workflowDepth;
    }

    public void setWorkflowDepth(Boolean workflowDepth) {
        this.workflowDepth = workflowDepth;
    }

    public String getScheduler() {
        return this.scheduler;
    }

    public void setScheduler(String scheduler) {
        this.scheduler = scheduler;
    }

    public String getJobName() {
        return this.jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public String getJobExecId() {
        return this.jobExecId;
    }

    public void setJobExecId(String jobExecId) {
        this.jobExecId = jobExecId;
    }

    public String getFlowExecId() {
        return this.flowExecId;
    }

    public void setFlowExecId(String flowExecId) {
        this.flowExecId = flowExecId;
    }

    public String getJobDefId() {
        return this.jobDefId;
    }

    public void setJobDefId(String jobDefId) {
        this.jobDefId = jobDefId;
    }

    public String getFlowDefId() {
        return this.flowDefId;
    }

    public void setFlowDefId(String flowDefId) {
        this.flowDefId = flowDefId;
    }

    public String getJobExecUrl() {
        return this.jobExecUrl;
    }

    public void setJobExecUrl(String jobExecUrl) {
        this.jobExecUrl = jobExecUrl;
    }

    public String getFlowExecUrl() {
        return this.flowExecUrl;
    }

    public void setFlowExecUrl(String flowExecUrl) {
        this.flowExecUrl = flowExecUrl;
    }

    public String getJobDefUrl() {
        return this.jobDefUrl;
    }

    public void setJobDefUrl(String jobDefUrl) {
        this.jobDefUrl = jobDefUrl;
    }

    public String getFlowDefUrl() {
        return this.flowDefUrl;
    }

    public void setFlowDefUrl(String flowDefUrl) {
        this.flowDefUrl = flowDefUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("YarnAppResult (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(username);
        sb.append(", ").append(queueName);
        sb.append(", ").append(startTime);
        sb.append(", ").append(finishTime);
        sb.append(", ").append(recordTs);
        sb.append(", ").append(trackingUrl);
        sb.append(", ").append(jobType);
        sb.append(", ").append(severity);
        sb.append(", ").append(score);
        sb.append(", ").append(workflowDepth);
        sb.append(", ").append(scheduler);
        sb.append(", ").append(jobName);
        sb.append(", ").append(jobExecId);
        sb.append(", ").append(flowExecId);
        sb.append(", ").append(jobDefId);
        sb.append(", ").append(flowDefId);
        sb.append(", ").append(jobExecUrl);
        sb.append(", ").append(flowExecUrl);
        sb.append(", ").append(jobDefUrl);
        sb.append(", ").append(flowDefUrl);

        sb.append(")");
        return sb.toString();
    }
}
