/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppHeuristicResultDetails implements Serializable {

    private static final long serialVersionUID = -1810473770;

    private Integer yarnAppHeuristicResultId;
    private String  name;
    private String  value;
    private String  details;

    public YarnAppHeuristicResultDetails() {}

    public YarnAppHeuristicResultDetails(YarnAppHeuristicResultDetails value) {
        this.yarnAppHeuristicResultId = value.yarnAppHeuristicResultId;
        this.name = value.name;
        this.value = value.value;
        this.details = value.details;
    }

    public YarnAppHeuristicResultDetails(
        Integer yarnAppHeuristicResultId,
        String  name,
        String  value,
        String  details
    ) {
        this.yarnAppHeuristicResultId = yarnAppHeuristicResultId;
        this.name = name;
        this.value = value;
        this.details = details;
    }

    public Integer getYarnAppHeuristicResultId() {
        return this.yarnAppHeuristicResultId;
    }

    public void setYarnAppHeuristicResultId(Integer yarnAppHeuristicResultId) {
        this.yarnAppHeuristicResultId = yarnAppHeuristicResultId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getDetails() {
        return this.details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("YarnAppHeuristicResultDetails (");

        sb.append(yarnAppHeuristicResultId);
        sb.append(", ").append(name);
        sb.append(", ").append(value);
        sb.append(", ").append(details);

        sb.append(")");
        return sb.toString();
    }
}
