/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.AlarmMessage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmMessageRecord extends UpdatableRecordImpl<AlarmMessageRecord> implements Record6<Long, String, Long, String, String, Short> {

    private static final long serialVersionUID = 643570674;

    /**
     * Setter for <code>cloudins_apm.alarm_message.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins_apm.alarm_message.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins_apm.alarm_message.trace_id</code>.
     */
    public void setTraceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins_apm.alarm_message.trace_id</code>.
     */
    public String getTraceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins_apm.alarm_message.region</code>.
     */
    public void setRegion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins_apm.alarm_message.region</code>.
     */
    public Long getRegion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>cloudins_apm.alarm_message.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins_apm.alarm_message.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins_apm.alarm_message.time</code>.
     */
    public void setTime(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins_apm.alarm_message.time</code>.
     */
    public String getTime() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloudins_apm.alarm_message.status</code>.
     */
    public void setStatus(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins_apm.alarm_message.status</code>.
     */
    public Short getStatus() {
        return (Short) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, String, String, Short> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, String, String, Short> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AlarmMessage.ALARM_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AlarmMessage.ALARM_MESSAGE.TRACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return AlarmMessage.ALARM_MESSAGE.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AlarmMessage.ALARM_MESSAGE.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AlarmMessage.ALARM_MESSAGE.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return AlarmMessage.ALARM_MESSAGE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTraceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessageRecord value2(String value) {
        setTraceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessageRecord value3(Long value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessageRecord value4(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessageRecord value5(String value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessageRecord value6(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessageRecord values(Long value1, String value2, Long value3, String value4, String value5, Short value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlarmMessageRecord
     */
    public AlarmMessageRecord() {
        super(AlarmMessage.ALARM_MESSAGE);
    }

    /**
     * Create a detached, initialised AlarmMessageRecord
     */
    public AlarmMessageRecord(Long id, String traceId, Long region, String message, String time, Short status) {
        super(AlarmMessage.ALARM_MESSAGE);

        set(0, id);
        set(1, traceId);
        set(2, region);
        set(3, message);
        set(4, time);
        set(5, status);
    }
}
