/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.CloudinsField;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsFieldRecord extends UpdatableRecordImpl<CloudinsFieldRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -682841049;

    /**
     * Setter for <code>cloudins.cloudins_field.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_field.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cloudins.cloudins_field.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_field.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins.cloudins_field.host_ip</code>.
     */
    public void setHostIp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_field.host_ip</code>.
     */
    public String getHostIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins.cloudins_field.host_username</code>.
     */
    public void setHostUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_field.host_username</code>.
     */
    public String getHostUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins.cloudins_field.host_password</code>.
     */
    public void setHostPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_field.host_password</code>.
     */
    public String getHostPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloudins.cloudins_field.remark</code>.
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_field.remark</code>.
     */
    public String getRemark() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CloudinsField.CLOUDINS_FIELD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CloudinsField.CLOUDINS_FIELD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CloudinsField.CLOUDINS_FIELD.HOST_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CloudinsField.CLOUDINS_FIELD.HOST_USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CloudinsField.CLOUDINS_FIELD.HOST_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CloudinsField.CLOUDINS_FIELD.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getHostIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getHostUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHostPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldRecord value3(String value) {
        setHostIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldRecord value4(String value) {
        setHostUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldRecord value5(String value) {
        setHostPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldRecord value6(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CloudinsFieldRecord
     */
    public CloudinsFieldRecord() {
        super(CloudinsField.CLOUDINS_FIELD);
    }

    /**
     * Create a detached, initialised CloudinsFieldRecord
     */
    public CloudinsFieldRecord(Integer id, String name, String hostIp, String hostUsername, String hostPassword, String remark) {
        super(CloudinsField.CLOUDINS_FIELD);

        set(0, id);
        set(1, name);
        set(2, hostIp);
        set(3, hostUsername);
        set(4, hostPassword);
        set(5, remark);
    }
}
