/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.CloudinsUserRegionAppli;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsUserRegionAppliRecord extends UpdatableRecordImpl<CloudinsUserRegionAppliRecord> implements Record8<Long, Long, String, Long, String, String, String, String> {

    private static final long serialVersionUID = 1196190420;

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.region_id</code>.
     */
    public void setRegionId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.region_id</code>.
     */
    public Long getRegionId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.region_name</code>.
     */
    public void setRegionName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.region_name</code>.
     */
    public String getRegionName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.appli_msg</code>.
     */
    public void setAppliMsg(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.appli_msg</code>.
     */
    public String getAppliMsg() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_user_region_appli.reply_msg</code>.
     */
    public void setReplyMsg(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_user_region_appli.reply_msg</code>.
     */
    public String getReplyMsg() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, Long, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, Long, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.REGION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.APPLI_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI.REPLY_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRegionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAppliMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getReplyMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value3(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value4(Long value) {
        setRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value5(String value) {
        setRegionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value7(String value) {
        setAppliMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord value8(String value) {
        setReplyMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppliRecord values(Long value1, Long value2, String value3, Long value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CloudinsUserRegionAppliRecord
     */
    public CloudinsUserRegionAppliRecord() {
        super(CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI);
    }

    /**
     * Create a detached, initialised CloudinsUserRegionAppliRecord
     */
    public CloudinsUserRegionAppliRecord(Long id, Long userId, String userName, Long regionId, String regionName, String status, String appliMsg, String replyMsg) {
        super(CloudinsUserRegionAppli.CLOUDINS_USER_REGION_APPLI);

        set(0, id);
        set(1, userId);
        set(2, userName);
        set(3, regionId);
        set(4, regionName);
        set(5, status);
        set(6, appliMsg);
        set(7, replyMsg);
    }
}
