/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.CloudinsSpanBaseline;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsSpanBaselineRecord extends UpdatableRecordImpl<CloudinsSpanBaselineRecord> implements Record7<Long, Long, String, String, Long, Long, Long> {

    private static final long serialVersionUID = -34850003;

    /**
     * Setter for <code>cloudins_apm.cloudins_span_baseline.trace_id</code>.
     */
    public void setTraceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_span_baseline.trace_id</code>.
     */
    public Long getTraceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_span_baseline.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_span_baseline.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_span_baseline.trace_md5</code>.
     */
    public void setTraceMd5(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_span_baseline.trace_md5</code>.
     */
    public String getTraceMd5() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_span_baseline.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_span_baseline.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_span_baseline.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_span_baseline.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_span_baseline.start_ts</code>. Span.timestamp(): epoch micros used for endTs query and to implement TTL
     */
    public void setStartTs(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_span_baseline.start_ts</code>. Span.timestamp(): epoch micros used for endTs query and to implement TTL
     */
    public Long getStartTs() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>cloudins_apm.cloudins_span_baseline.duration</code>. Span.duration(): micros used for minDuration and maxDuration query
     */
    public void setDuration(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins_apm.cloudins_span_baseline.duration</code>. Span.duration(): micros used for minDuration and maxDuration query
     */
    public Long getDuration() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, Long, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, Long, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE.TRACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE.TRACE_MD5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE.START_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTraceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTraceMd5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getStartTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord value1(Long value) {
        setTraceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord value2(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord value3(String value) {
        setTraceMd5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord value5(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord value6(Long value) {
        setStartTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord value7(Long value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaselineRecord values(Long value1, Long value2, String value3, String value4, Long value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CloudinsSpanBaselineRecord
     */
    public CloudinsSpanBaselineRecord() {
        super(CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE);
    }

    /**
     * Create a detached, initialised CloudinsSpanBaselineRecord
     */
    public CloudinsSpanBaselineRecord(Long traceId, Long id, String traceMd5, String name, Long parentId, Long startTs, Long duration) {
        super(CloudinsSpanBaseline.CLOUDINS_SPAN_BASELINE);

        set(0, traceId);
        set(1, id);
        set(2, traceMd5);
        set(3, name);
        set(4, parentId);
        set(5, startTs);
        set(6, duration);
    }
}
