/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.CloudinsConfig;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsConfigRecord extends UpdatableRecordImpl<CloudinsConfigRecord> implements Record8<Long, String, String, String, String, String, Integer, String> {

    private static final long serialVersionUID = -2970964;

    /**
     * Setter for <code>cloudins.cloudins_config.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins.cloudins_config.product</code>. cloudins产品名称，如generater、analyzer等
     */
    public void setProduct(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.product</code>. cloudins产品名称，如generater、analyzer等
     */
    public String getProduct() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins.cloudins_config.module</code>. config中的分类，如db, parameter,connection等
     */
    public void setModule(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.module</code>. config中的分类，如db, parameter,connection等
     */
    public String getModule() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins.cloudins_config.parm_alias</code>.
     */
    public void setParmAlias(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.parm_alias</code>.
     */
    public String getParmAlias() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins.cloudins_config.parm_name</code>.
     */
    public void setParmName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.parm_name</code>.
     */
    public String getParmName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloudins.cloudins_config.parm_value</code>.
     */
    public void setParmValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.parm_value</code>.
     */
    public String getParmValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cloudins.cloudins_config.flag</code>. 预留字段
     */
    public void setFlag(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.flag</code>. 预留字段
     */
    public Integer getFlag() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>cloudins.cloudins_config.comment</code>.
     */
    public void setComment(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloudins.cloudins_config.comment</code>.
     */
    public String getComment() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, String, Integer, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, String, Integer, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CloudinsConfig.CLOUDINS_CONFIG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CloudinsConfig.CLOUDINS_CONFIG.PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CloudinsConfig.CLOUDINS_CONFIG.MODULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CloudinsConfig.CLOUDINS_CONFIG.PARM_ALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CloudinsConfig.CLOUDINS_CONFIG.PARM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CloudinsConfig.CLOUDINS_CONFIG.PARM_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return CloudinsConfig.CLOUDINS_CONFIG.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CloudinsConfig.CLOUDINS_CONFIG.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getModule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getParmAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getParmName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getParmValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value2(String value) {
        setProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value3(String value) {
        setModule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value4(String value) {
        setParmAlias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value5(String value) {
        setParmName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value6(String value) {
        setParmValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value7(Integer value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord value8(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfigRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Integer value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CloudinsConfigRecord
     */
    public CloudinsConfigRecord() {
        super(CloudinsConfig.CLOUDINS_CONFIG);
    }

    /**
     * Create a detached, initialised CloudinsConfigRecord
     */
    public CloudinsConfigRecord(Long id, String product, String module, String parmAlias, String parmName, String parmValue, Integer flag, String comment) {
        super(CloudinsConfig.CLOUDINS_CONFIG);

        set(0, id);
        set(1, product);
        set(2, module);
        set(3, parmAlias);
        set(4, parmName);
        set(5, parmValue);
        set(6, flag);
        set(7, comment);
    }
}
