/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.HistoricalPeak;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoricalPeakRecord extends UpdatableRecordImpl<HistoricalPeakRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 407728690;

    /**
     * Setter for <code>cloudins.historical_peak.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins.historical_peak.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cloudins.historical_peak.summary_date</code>.
     */
    public void setSummaryDate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins.historical_peak.summary_date</code>.
     */
    public String getSummaryDate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins.historical_peak.start_time</code>.
     */
    public void setStartTime(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins.historical_peak.start_time</code>.
     */
    public String getStartTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins.historical_peak.end_time</code>.
     */
    public void setEndTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins.historical_peak.end_time</code>.
     */
    public String getEndTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins.historical_peak.trigger_job_num</code>.
     */
    public void setTriggerJobNum(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins.historical_peak.trigger_job_num</code>.
     */
    public String getTriggerJobNum() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloudins.historical_peak.end_job_num</code>.
     */
    public void setEndJobNum(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins.historical_peak.end_job_num</code>.
     */
    public String getEndJobNum() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return HistoricalPeak.HISTORICAL_PEAK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return HistoricalPeak.HISTORICAL_PEAK.SUMMARY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return HistoricalPeak.HISTORICAL_PEAK.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return HistoricalPeak.HISTORICAL_PEAK.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return HistoricalPeak.HISTORICAL_PEAK.TRIGGER_JOB_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return HistoricalPeak.HISTORICAL_PEAK.END_JOB_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSummaryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTriggerJobNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEndJobNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HistoricalPeakRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HistoricalPeakRecord value2(String value) {
        setSummaryDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HistoricalPeakRecord value3(String value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HistoricalPeakRecord value4(String value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HistoricalPeakRecord value5(String value) {
        setTriggerJobNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HistoricalPeakRecord value6(String value) {
        setEndJobNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HistoricalPeakRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HistoricalPeakRecord
     */
    public HistoricalPeakRecord() {
        super(HistoricalPeak.HISTORICAL_PEAK);
    }

    /**
     * Create a detached, initialised HistoricalPeakRecord
     */
    public HistoricalPeakRecord(Integer id, String summaryDate, String startTime, String endTime, String triggerJobNum, String endJobNum) {
        super(HistoricalPeak.HISTORICAL_PEAK);

        set(0, id);
        set(1, summaryDate);
        set(2, startTime);
        set(3, endTime);
        set(4, triggerJobNum);
        set(5, endJobNum);
    }
}
