/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.SpansBackup;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record2;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpansBackupRecord extends UpdatableRecordImpl<SpansBackupRecord> implements Record11<Long, Long, Integer, String, Long, Long, Long, String, Long, Integer, String> {

    private static final long serialVersionUID = 312232096;

    /**
     * Setter for <code>cloudins_apm.spans_backup.trace_id</code>.
     */
    public void setTraceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.trace_id</code>.
     */
    public Long getTraceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.span_id</code>.
     */
    public void setSpanId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.span_id</code>.
     */
    public Long getSpanId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.endpoint_ipv4</code>.
     */
    public void setEndpointIpv4(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.endpoint_ipv4</code>.
     */
    public Integer getEndpointIpv4() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.endpoint_service_name</code>.
     */
    public void setEndpointServiceName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.endpoint_service_name</code>.
     */
    public String getEndpointServiceName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.start_ts</code>.
     */
    public void setStartTs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.start_ts</code>.
     */
    public Long getStartTs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.duration</code>.
     */
    public void setDuration(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.duration</code>.
     */
    public Long getDuration() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.record_ts</code>.
     */
    public void setRecordTs(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.record_ts</code>.
     */
    public Long getRecordTs() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.trace_md5</code>.
     */
    public void setTraceMd5(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.trace_md5</code>.
     */
    public String getTraceMd5() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.parent_ip</code>.
     */
    public void setParentIp(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.parent_ip</code>.
     */
    public Integer getParentIp() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>cloudins_apm.spans_backup.parent_endpoint_name</code>.
     */
    public void setParentEndpointName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans_backup.parent_endpoint_name</code>.
     */
    public String getParentEndpointName() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Long, Integer, String, Long, Long, Long, String, Long, Integer, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Long, Integer, String, Long, Long, Long, String, Long, Integer, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SpansBackup.SPANS_BACKUP.TRACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SpansBackup.SPANS_BACKUP.SPAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SpansBackup.SPANS_BACKUP.ENDPOINT_IPV4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SpansBackup.SPANS_BACKUP.ENDPOINT_SERVICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SpansBackup.SPANS_BACKUP.START_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return SpansBackup.SPANS_BACKUP.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return SpansBackup.SPANS_BACKUP.RECORD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SpansBackup.SPANS_BACKUP.TRACE_MD5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return SpansBackup.SPANS_BACKUP.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return SpansBackup.SPANS_BACKUP.PARENT_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SpansBackup.SPANS_BACKUP.PARENT_ENDPOINT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTraceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSpanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEndpointIpv4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEndpointServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getStartTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getRecordTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTraceMd5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getParentIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getParentEndpointName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value1(Long value) {
        setTraceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value2(Long value) {
        setSpanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value3(Integer value) {
        setEndpointIpv4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value4(String value) {
        setEndpointServiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value5(Long value) {
        setStartTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value6(Long value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value7(Long value) {
        setRecordTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value8(String value) {
        setTraceMd5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value9(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value10(Integer value) {
        setParentIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord value11(String value) {
        setParentEndpointName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansBackupRecord values(Long value1, Long value2, Integer value3, String value4, Long value5, Long value6, Long value7, String value8, Long value9, Integer value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpansBackupRecord
     */
    public SpansBackupRecord() {
        super(SpansBackup.SPANS_BACKUP);
    }

    /**
     * Create a detached, initialised SpansBackupRecord
     */
    public SpansBackupRecord(Long traceId, Long spanId, Integer endpointIpv4, String endpointServiceName, Long startTs, Long duration, Long recordTs, String traceMd5, Long parentId, Integer parentIp, String parentEndpointName) {
        super(SpansBackup.SPANS_BACKUP);

        set(0, traceId);
        set(1, spanId);
        set(2, endpointIpv4);
        set(3, endpointServiceName);
        set(4, startTs);
        set(5, duration);
        set(6, recordTs);
        set(7, traceMd5);
        set(8, parentId);
        set(9, parentIp);
        set(10, parentEndpointName);
    }
}
