/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.Spans;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpansRecord extends UpdatableRecordImpl<SpansRecord> implements Record7<Long, Long, Integer, String, Long, Long, Long> {

    private static final long serialVersionUID = 1537715884;

    /**
     * Setter for <code>cloudins_apm.spans.trace_id</code>.
     */
    public void setTraceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans.trace_id</code>.
     */
    public Long getTraceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins_apm.spans.span_id</code>.
     */
    public void setSpanId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans.span_id</code>.
     */
    public Long getSpanId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cloudins_apm.spans.endpoint_ipv4</code>.
     */
    public void setEndpointIpv4(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans.endpoint_ipv4</code>.
     */
    public Integer getEndpointIpv4() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cloudins_apm.spans.endpoint_service_name</code>.
     */
    public void setEndpointServiceName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans.endpoint_service_name</code>.
     */
    public String getEndpointServiceName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins_apm.spans.start_ts</code>.
     */
    public void setStartTs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans.start_ts</code>.
     */
    public Long getStartTs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>cloudins_apm.spans.duration</code>.
     */
    public void setDuration(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans.duration</code>.
     */
    public Long getDuration() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>cloudins_apm.spans.record_ts</code>.
     */
    public void setRecordTs(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins_apm.spans.record_ts</code>.
     */
    public Long getRecordTs() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Integer, String, Long, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Integer, String, Long, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Spans.SPANS.TRACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Spans.SPANS.SPAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Spans.SPANS.ENDPOINT_IPV4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Spans.SPANS.ENDPOINT_SERVICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Spans.SPANS.START_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Spans.SPANS.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Spans.SPANS.RECORD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTraceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSpanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEndpointIpv4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEndpointServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getStartTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getRecordTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord value1(Long value) {
        setTraceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord value2(Long value) {
        setSpanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord value3(Integer value) {
        setEndpointIpv4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord value4(String value) {
        setEndpointServiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord value5(Long value) {
        setStartTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord value6(Long value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord value7(Long value) {
        setRecordTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpansRecord values(Long value1, Long value2, Integer value3, String value4, Long value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpansRecord
     */
    public SpansRecord() {
        super(Spans.SPANS);
    }

    /**
     * Create a detached, initialised SpansRecord
     */
    public SpansRecord(Long traceId, Long spanId, Integer endpointIpv4, String endpointServiceName, Long startTs, Long duration, Long recordTs) {
        super(Spans.SPANS);

        set(0, traceId);
        set(1, spanId);
        set(2, endpointIpv4);
        set(3, endpointServiceName);
        set(4, startTs);
        set(5, duration);
        set(6, recordTs);
    }
}
