/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.StatisticsSpans;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatisticsSpansRecord extends UpdatableRecordImpl<StatisticsSpansRecord> implements Record9<Integer, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1163308435;

    /**
     * Setter for <code>cloudins_apm.statistics_spans.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.start_time</code>.
     */
    public void setStartTime(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.start_time</code>.
     */
    public String getStartTime() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.end_time</code>.
     */
    public void setEndTime(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.end_time</code>.
     */
    public String getEndTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.span_name</code>. 关联到span_infos表中的name
     */
    public void setSpanName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.span_name</code>. 关联到span_infos表中的name
     */
    public String getSpanName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.called_num</code>. 特定时间段内特定span被调用的次数
     */
    public void setCalledNum(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.called_num</code>. 特定时间段内特定span被调用的次数
     */
    public String getCalledNum() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.avg_time</code>.
     */
    public void setAvgTime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.avg_time</code>.
     */
    public String getAvgTime() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.slowest_id</code>.
     */
    public void setSlowestId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.slowest_id</code>.
     */
    public String getSlowestId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.slowest_time</code>.
     */
    public void setSlowestTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.slowest_time</code>.
     */
    public String getSlowestTime() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cloudins_apm.statistics_spans.slowest_host</code>.
     */
    public void setSlowestHost(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloudins_apm.statistics_spans.slowest_host</code>.
     */
    public String getSlowestHost() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StatisticsSpans.STATISTICS_SPANS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StatisticsSpans.STATISTICS_SPANS.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StatisticsSpans.STATISTICS_SPANS.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return StatisticsSpans.STATISTICS_SPANS.SPAN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return StatisticsSpans.STATISTICS_SPANS.CALLED_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return StatisticsSpans.STATISTICS_SPANS.AVG_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return StatisticsSpans.STATISTICS_SPANS.SLOWEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return StatisticsSpans.STATISTICS_SPANS.SLOWEST_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return StatisticsSpans.STATISTICS_SPANS.SLOWEST_HOST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSpanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCalledNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAvgTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSlowestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSlowestTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSlowestHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value2(String value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value3(String value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value4(String value) {
        setSpanName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value5(String value) {
        setCalledNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value6(String value) {
        setAvgTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value7(String value) {
        setSlowestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value8(String value) {
        setSlowestTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord value9(String value) {
        setSlowestHost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatisticsSpansRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatisticsSpansRecord
     */
    public StatisticsSpansRecord() {
        super(StatisticsSpans.STATISTICS_SPANS);
    }

    /**
     * Create a detached, initialised StatisticsSpansRecord
     */
    public StatisticsSpansRecord(Integer id, String startTime, String endTime, String spanName, String calledNum, String avgTime, String slowestId, String slowestTime, String slowestHost) {
        super(StatisticsSpans.STATISTICS_SPANS);

        set(0, id);
        set(1, startTime);
        set(2, endTime);
        set(3, spanName);
        set(4, calledNum);
        set(5, avgTime);
        set(6, slowestId);
        set(7, slowestTime);
        set(8, slowestHost);
    }
}
