/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.SysConfigs;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysConfigsRecord extends UpdatableRecordImpl<SysConfigsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 731086968;

    /**
     * Setter for <code>cloudins.sys_configs.config_name</code>.
     */
    public void setConfigName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins.sys_configs.config_name</code>.
     */
    public String getConfigName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cloudins.sys_configs.config_value</code>.
     */
    public void setConfigValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins.sys_configs.config_value</code>.
     */
    public String getConfigValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysConfigs.SYS_CONFIGS.CONFIG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysConfigs.SYS_CONFIGS.CONFIG_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getConfigName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getConfigValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysConfigsRecord value1(String value) {
        setConfigName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysConfigsRecord value2(String value) {
        setConfigValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysConfigsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysConfigsRecord
     */
    public SysConfigsRecord() {
        super(SysConfigs.SYS_CONFIGS);
    }

    /**
     * Create a detached, initialised SysConfigsRecord
     */
    public SysConfigsRecord(String configName, String configValue) {
        super(SysConfigs.SYS_CONFIGS);

        set(0, configName);
        set(1, configValue);
    }
}
