/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.YarnAppResult;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppResultRecord extends UpdatableRecordImpl<YarnAppResultRecord> implements Record22<String, String, String, String, ULong, ULong, Long, String, String, Boolean, UInteger, Boolean, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 701073183;

    /**
     * Setter for <code>cloudins.yarn_app_result.id</code>. The application id, e.g., application_1236543456321_1234567
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.id</code>. The application id, e.g., application_1236543456321_1234567
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.name</code>. The application name
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.name</code>. The application name
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.username</code>. The user who started the application
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.username</code>. The user who started the application
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.queue_name</code>. The queue the application was submitted to
     */
    public void setQueueName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.queue_name</code>. The queue the application was submitted to
     */
    public String getQueueName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.start_time</code>. The time in which application started
     */
    public void setStartTime(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.start_time</code>. The time in which application started
     */
    public ULong getStartTime() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.finish_time</code>. The time in which application finished
     */
    public void setFinishTime(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.finish_time</code>. The time in which application finished
     */
    public ULong getFinishTime() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.record_ts</code>.
     */
    public void setRecordTs(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.record_ts</code>.
     */
    public Long getRecordTs() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.tracking_url</code>. The web URL that can be used to track the application
     */
    public void setTrackingUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.tracking_url</code>. The web URL that can be used to track the application
     */
    public String getTrackingUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.job_type</code>. The Job Type e.g, Pig, Hive, Spark, HadoopJava
     */
    public void setJobType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.job_type</code>. The Job Type e.g, Pig, Hive, Spark, HadoopJava
     */
    public String getJobType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.severity</code>. Aggregate severity of all the heuristics. Ranges from 0(LOW) to 4(CRITICAL)
     */
    public void setSeverity(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.severity</code>. Aggregate severity of all the heuristics. Ranges from 0(LOW) to 4(CRITICAL)
     */
    public Boolean getSeverity() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.score</code>. The application score which is the sum of heuristic scores
     */
    public void setScore(UInteger value) {
        set(10, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.score</code>. The application score which is the sum of heuristic scores
     */
    public UInteger getScore() {
        return (UInteger) get(10);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.workflow_depth</code>. The application depth in the scheduled flow. Depth starts from 0
     */
    public void setWorkflowDepth(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.workflow_depth</code>. The application depth in the scheduled flow. Depth starts from 0
     */
    public Boolean getWorkflowDepth() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.scheduler</code>. The scheduler which triggered the application
     */
    public void setScheduler(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.scheduler</code>. The scheduler which triggered the application
     */
    public String getScheduler() {
        return (String) get(12);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.job_name</code>. The name of the job in the flow to which this app belongs
     */
    public void setJobName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.job_name</code>. The name of the job in the flow to which this app belongs
     */
    public String getJobName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.job_exec_id</code>. A unique reference to a specific execution of the job/action(job in the workflow). This should filter all applications (mapreduce/spark) triggered by the job for a particular execution.
     */
    public void setJobExecId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.job_exec_id</code>. A unique reference to a specific execution of the job/action(job in the workflow). This should filter all applications (mapreduce/spark) triggered by the job for a particular execution.
     */
    public String getJobExecId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.flow_exec_id</code>. A unique reference to a specific flow execution. This should filter all applications fired by a particular flow execution. Note that if the scheduler supports sub-workflows, then this ID should be the super parent flow execution id that triggered the the applications and sub-workflows.
     */
    public void setFlowExecId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.flow_exec_id</code>. A unique reference to a specific flow execution. This should filter all applications fired by a particular flow execution. Note that if the scheduler supports sub-workflows, then this ID should be the super parent flow execution id that triggered the the applications and sub-workflows.
     */
    public String getFlowExecId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.job_def_id</code>. A unique reference to the job in the entire flow independent of the execution. This should filter all the applications(mapreduce/spark) triggered by the job for all the historic executions of that job.
     */
    public void setJobDefId(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.job_def_id</code>. A unique reference to the job in the entire flow independent of the execution. This should filter all the applications(mapreduce/spark) triggered by the job for all the historic executions of that job.
     */
    public String getJobDefId() {
        return (String) get(16);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.flow_def_id</code>. A unique reference to the entire flow independent of any execution. This should filter all the historic mr jobs belonging to the flow. Note that if your scheduler supports sub-workflows, then this ID should reference the super parent flow that triggered the all the jobs and sub-workflows.
     */
    public void setFlowDefId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.flow_def_id</code>. A unique reference to the entire flow independent of any execution. This should filter all the historic mr jobs belonging to the flow. Note that if your scheduler supports sub-workflows, then this ID should reference the super parent flow that triggered the all the jobs and sub-workflows.
     */
    public String getFlowDefId() {
        return (String) get(17);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.job_exec_url</code>. A url to the job execution on the scheduler
     */
    public void setJobExecUrl(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.job_exec_url</code>. A url to the job execution on the scheduler
     */
    public String getJobExecUrl() {
        return (String) get(18);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.flow_exec_url</code>. A url to the flow execution on the scheduler
     */
    public void setFlowExecUrl(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.flow_exec_url</code>. A url to the flow execution on the scheduler
     */
    public String getFlowExecUrl() {
        return (String) get(19);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.job_def_url</code>. A url to the job definition on the scheduler
     */
    public void setJobDefUrl(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.job_def_url</code>. A url to the job definition on the scheduler
     */
    public String getJobDefUrl() {
        return (String) get(20);
    }

    /**
     * Setter for <code>cloudins.yarn_app_result.flow_def_url</code>. A url to the flow definition on the scheduler
     */
    public void setFlowDefUrl(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_result.flow_def_url</code>. A url to the flow definition on the scheduler
     */
    public String getFlowDefUrl() {
        return (String) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<String, String, String, String, ULong, ULong, Long, String, String, Boolean, UInteger, Boolean, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<String, String, String, String, ULong, ULong, Long, String, String, Boolean, UInteger, Boolean, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return YarnAppResult.YARN_APP_RESULT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return YarnAppResult.YARN_APP_RESULT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return YarnAppResult.YARN_APP_RESULT.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return YarnAppResult.YARN_APP_RESULT.QUEUE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return YarnAppResult.YARN_APP_RESULT.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return YarnAppResult.YARN_APP_RESULT.FINISH_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return YarnAppResult.YARN_APP_RESULT.RECORD_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return YarnAppResult.YARN_APP_RESULT.TRACKING_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return YarnAppResult.YARN_APP_RESULT.JOB_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return YarnAppResult.YARN_APP_RESULT.SEVERITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field11() {
        return YarnAppResult.YARN_APP_RESULT.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return YarnAppResult.YARN_APP_RESULT.WORKFLOW_DEPTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return YarnAppResult.YARN_APP_RESULT.SCHEDULER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return YarnAppResult.YARN_APP_RESULT.JOB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return YarnAppResult.YARN_APP_RESULT.JOB_EXEC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return YarnAppResult.YARN_APP_RESULT.FLOW_EXEC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return YarnAppResult.YARN_APP_RESULT.JOB_DEF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return YarnAppResult.YARN_APP_RESULT.FLOW_DEF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return YarnAppResult.YARN_APP_RESULT.JOB_EXEC_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return YarnAppResult.YARN_APP_RESULT.FLOW_EXEC_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field21() {
        return YarnAppResult.YARN_APP_RESULT.JOB_DEF_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field22() {
        return YarnAppResult.YARN_APP_RESULT.FLOW_DEF_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getQueueName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getFinishTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getRecordTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTrackingUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getJobType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getSeverity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value11() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getWorkflowDepth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getScheduler();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getJobExecId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getFlowExecId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getJobDefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getFlowDefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getJobExecUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getFlowExecUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value21() {
        return getJobDefUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value22() {
        return getFlowDefUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value3(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value4(String value) {
        setQueueName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value5(ULong value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value6(ULong value) {
        setFinishTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value7(Long value) {
        setRecordTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value8(String value) {
        setTrackingUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value9(String value) {
        setJobType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value10(Boolean value) {
        setSeverity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value11(UInteger value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value12(Boolean value) {
        setWorkflowDepth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value13(String value) {
        setScheduler(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value14(String value) {
        setJobName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value15(String value) {
        setJobExecId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value16(String value) {
        setFlowExecId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value17(String value) {
        setJobDefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value18(String value) {
        setFlowDefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value19(String value) {
        setJobExecUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value20(String value) {
        setFlowExecUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value21(String value) {
        setJobDefUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord value22(String value) {
        setFlowDefUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResultRecord values(String value1, String value2, String value3, String value4, ULong value5, ULong value6, Long value7, String value8, String value9, Boolean value10, UInteger value11, Boolean value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20, String value21, String value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YarnAppResultRecord
     */
    public YarnAppResultRecord() {
        super(YarnAppResult.YARN_APP_RESULT);
    }

    /**
     * Create a detached, initialised YarnAppResultRecord
     */
    public YarnAppResultRecord(String id, String name, String username, String queueName, ULong startTime, ULong finishTime, Long recordTs, String trackingUrl, String jobType, Boolean severity, UInteger score, Boolean workflowDepth, String scheduler, String jobName, String jobExecId, String flowExecId, String jobDefId, String flowDefId, String jobExecUrl, String flowExecUrl, String jobDefUrl, String flowDefUrl) {
        super(YarnAppResult.YARN_APP_RESULT);

        set(0, id);
        set(1, name);
        set(2, username);
        set(3, queueName);
        set(4, startTime);
        set(5, finishTime);
        set(6, recordTs);
        set(7, trackingUrl);
        set(8, jobType);
        set(9, severity);
        set(10, score);
        set(11, workflowDepth);
        set(12, scheduler);
        set(13, jobName);
        set(14, jobExecId);
        set(15, flowExecId);
        set(16, jobDefId);
        set(17, flowDefId);
        set(18, jobExecUrl);
        set(19, flowExecUrl);
        set(20, jobDefUrl);
        set(21, flowDefUrl);
    }
}
