/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.YarnAppCheckLog;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppCheckLogRecord extends UpdatableRecordImpl<YarnAppCheckLogRecord> implements Record7<Long, String, String, String, String, Boolean, Boolean> {

    private static final long serialVersionUID = 629690716;

    /**
     * Setter for <code>cloudins.yarn_app_check_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_check_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins.yarn_app_check_log.app_id</code>.
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_check_log.app_id</code>.
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins.yarn_app_check_log.message</code>.
     */
    public void setMessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_check_log.message</code>.
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins.yarn_app_check_log.time</code>.
     */
    public void setTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_check_log.time</code>.
     */
    public String getTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cloudins.yarn_app_check_log.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_check_log.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cloudins.yarn_app_check_log.displayed</code>.
     */
    public void setDisplayed(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_check_log.displayed</code>.
     */
    public Boolean getDisplayed() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>cloudins.yarn_app_check_log.isread</code>.
     */
    public void setIsread(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_check_log.isread</code>.
     */
    public Boolean getIsread() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, Boolean, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, Boolean, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return YarnAppCheckLog.YARN_APP_CHECK_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return YarnAppCheckLog.YARN_APP_CHECK_LOG.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return YarnAppCheckLog.YARN_APP_CHECK_LOG.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return YarnAppCheckLog.YARN_APP_CHECK_LOG.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return YarnAppCheckLog.YARN_APP_CHECK_LOG.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return YarnAppCheckLog.YARN_APP_CHECK_LOG.DISPLAYED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return YarnAppCheckLog.YARN_APP_CHECK_LOG.ISREAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDisplayed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getIsread();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord value2(String value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord value3(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord value4(String value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord value5(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord value6(Boolean value) {
        setDisplayed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord value7(Boolean value) {
        setIsread(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckLogRecord values(Long value1, String value2, String value3, String value4, String value5, Boolean value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YarnAppCheckLogRecord
     */
    public YarnAppCheckLogRecord() {
        super(YarnAppCheckLog.YARN_APP_CHECK_LOG);
    }

    /**
     * Create a detached, initialised YarnAppCheckLogRecord
     */
    public YarnAppCheckLogRecord(Long id, String appId, String message, String time, String type, Boolean displayed, Boolean isread) {
        super(YarnAppCheckLog.YARN_APP_CHECK_LOG);

        set(0, id);
        set(1, appId);
        set(2, message);
        set(3, time);
        set(4, type);
        set(5, displayed);
        set(6, isread);
    }
}
