/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.YarnAppHeuristicResultDetails;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppHeuristicResultDetailsRecord extends UpdatableRecordImpl<YarnAppHeuristicResultDetailsRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = -1305699904;

    /**
     * Setter for <code>cloudins.yarn_app_heuristic_result_details.yarn_app_heuristic_result_id</code>. The application heuristic result id
     */
    public void setYarnAppHeuristicResultId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_heuristic_result_details.yarn_app_heuristic_result_id</code>. The application heuristic result id
     */
    public Integer getYarnAppHeuristicResultId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>cloudins.yarn_app_heuristic_result_details.name</code>. The analysis detail entry name/key
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_heuristic_result_details.name</code>. The analysis detail entry name/key
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cloudins.yarn_app_heuristic_result_details.value</code>. The analysis detail value corresponding to the name
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_heuristic_result_details.value</code>. The analysis detail value corresponding to the name
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins.yarn_app_heuristic_result_details.details</code>. More information on analysis details. e.g, stacktrace
     */
    public void setDetails(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins.yarn_app_heuristic_result_details.details</code>. More information on analysis details. e.g, stacktrace
     */
    public String getDetails() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return YarnAppHeuristicResultDetails.YARN_APP_HEURISTIC_RESULT_DETAILS.YARN_APP_HEURISTIC_RESULT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return YarnAppHeuristicResultDetails.YARN_APP_HEURISTIC_RESULT_DETAILS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return YarnAppHeuristicResultDetails.YARN_APP_HEURISTIC_RESULT_DETAILS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return YarnAppHeuristicResultDetails.YARN_APP_HEURISTIC_RESULT_DETAILS.DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getYarnAppHeuristicResultId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppHeuristicResultDetailsRecord value1(Integer value) {
        setYarnAppHeuristicResultId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppHeuristicResultDetailsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppHeuristicResultDetailsRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppHeuristicResultDetailsRecord value4(String value) {
        setDetails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppHeuristicResultDetailsRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YarnAppHeuristicResultDetailsRecord
     */
    public YarnAppHeuristicResultDetailsRecord() {
        super(YarnAppHeuristicResultDetails.YARN_APP_HEURISTIC_RESULT_DETAILS);
    }

    /**
     * Create a detached, initialised YarnAppHeuristicResultDetailsRecord
     */
    public YarnAppHeuristicResultDetailsRecord(Integer yarnAppHeuristicResultId, String name, String value, String details) {
        super(YarnAppHeuristicResultDetails.YARN_APP_HEURISTIC_RESULT_DETAILS);

        set(0, yarnAppHeuristicResultId);
        set(1, name);
        set(2, value);
        set(3, details);
    }
}
