/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.records;


import javax.annotation.Generated;

import jooq.data.tables.ZipkinAnnotations;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZipkinAnnotationsRecord extends TableRecordImpl<ZipkinAnnotationsRecord> implements Record10<Long, Long, String, byte[], Integer, Long, Integer, byte[], Short, String> {

    private static final long serialVersionUID = 1788870483;

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.trace_id</code>. coincides with zipkin_spans.trace_id
     */
    public void setTraceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.trace_id</code>. coincides with zipkin_spans.trace_id
     */
    public Long getTraceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.span_id</code>. coincides with zipkin_spans.id
     */
    public void setSpanId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.span_id</code>. coincides with zipkin_spans.id
     */
    public Long getSpanId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.a_key</code>. BinaryAnnotation.key or Annotation.value if type == -1
     */
    public void setAKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.a_key</code>. BinaryAnnotation.key or Annotation.value if type == -1
     */
    public String getAKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.a_value</code>. BinaryAnnotation.value(), which must be smaller than 64KB
     */
    public void setAValue(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.a_value</code>. BinaryAnnotation.value(), which must be smaller than 64KB
     */
    public byte[] getAValue() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.a_type</code>. BinaryAnnotation.type() or -1 if Annotation
     */
    public void setAType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.a_type</code>. BinaryAnnotation.type() or -1 if Annotation
     */
    public Integer getAType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.a_timestamp</code>. Used to implement TTL; Annotation.timestamp or zipkin_spans.timestamp
     */
    public void setATimestamp(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.a_timestamp</code>. Used to implement TTL; Annotation.timestamp or zipkin_spans.timestamp
     */
    public Long getATimestamp() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.endpoint_ipv4</code>. Null when Binary/Annotation.endpoint is null
     */
    public void setEndpointIpv4(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.endpoint_ipv4</code>. Null when Binary/Annotation.endpoint is null
     */
    public Integer getEndpointIpv4() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.endpoint_ipv6</code>. Null when Binary/Annotation.endpoint is null, or no IPv6 address
     */
    public void setEndpointIpv6(byte[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.endpoint_ipv6</code>. Null when Binary/Annotation.endpoint is null, or no IPv6 address
     */
    public byte[] getEndpointIpv6() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.endpoint_port</code>. Null when Binary/Annotation.endpoint is null
     */
    public void setEndpointPort(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.endpoint_port</code>. Null when Binary/Annotation.endpoint is null
     */
    public Short getEndpointPort() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>cloudins_apm.zipkin_annotations.endpoint_service_name</code>. Null when Binary/Annotation.endpoint is null
     */
    public void setEndpointServiceName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>cloudins_apm.zipkin_annotations.endpoint_service_name</code>. Null when Binary/Annotation.endpoint is null
     */
    public String getEndpointServiceName() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, String, byte[], Integer, Long, Integer, byte[], Short, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, String, byte[], Integer, Long, Integer, byte[], Short, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.TRACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.SPAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.A_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.A_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.A_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.A_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.ENDPOINT_IPV4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field8() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.ENDPOINT_IPV6;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field9() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.ENDPOINT_PORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ZipkinAnnotations.ZIPKIN_ANNOTATIONS.ENDPOINT_SERVICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTraceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSpanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getAValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getATimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getEndpointIpv4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value8() {
        return getEndpointIpv6();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value9() {
        return getEndpointPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEndpointServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value1(Long value) {
        setTraceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value2(Long value) {
        setSpanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value3(String value) {
        setAKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value4(byte[] value) {
        setAValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value5(Integer value) {
        setAType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value6(Long value) {
        setATimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value7(Integer value) {
        setEndpointIpv4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value8(byte[] value) {
        setEndpointIpv6(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value9(Short value) {
        setEndpointPort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord value10(String value) {
        setEndpointServiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinAnnotationsRecord values(Long value1, Long value2, String value3, byte[] value4, Integer value5, Long value6, Integer value7, byte[] value8, Short value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ZipkinAnnotationsRecord
     */
    public ZipkinAnnotationsRecord() {
        super(ZipkinAnnotations.ZIPKIN_ANNOTATIONS);
    }

    /**
     * Create a detached, initialised ZipkinAnnotationsRecord
     */
    public ZipkinAnnotationsRecord(Long traceId, Long spanId, String aKey, byte[] aValue, Integer aType, Long aTimestamp, Integer endpointIpv4, byte[] endpointIpv6, Short endpointPort, String endpointServiceName) {
        super(ZipkinAnnotations.ZIPKIN_ANNOTATIONS);

        set(0, traceId);
        set(1, spanId);
        set(2, aKey);
        set(3, aValue);
        set(4, aType);
        set(5, aTimestamp);
        set(6, endpointIpv4);
        set(7, endpointIpv6);
        set(8, endpointPort);
        set(9, endpointServiceName);
    }
}
