/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.AlarmMessageRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmMessage extends TableImpl<AlarmMessageRecord> {

    private static final long serialVersionUID = 577443940;

    /**
     * The reference instance of <code>cloudins_apm.alarm_message</code>
     */
    public static final AlarmMessage ALARM_MESSAGE = new AlarmMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlarmMessageRecord> getRecordType() {
        return AlarmMessageRecord.class;
    }

    /**
     * The column <code>cloudins_apm.alarm_message.id</code>.
     */
    public final TableField<AlarmMessageRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.alarm_message.trace_id</code>.
     */
    public final TableField<AlarmMessageRecord, String> TRACE_ID = createField("trace_id", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.alarm_message.region</code>.
     */
    public final TableField<AlarmMessageRecord, Long> REGION = createField("region", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.alarm_message.message</code>.
     */
    public final TableField<AlarmMessageRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.alarm_message.time</code>.
     */
    public final TableField<AlarmMessageRecord, String> TIME = createField("time", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.alarm_message.status</code>.
     */
    public final TableField<AlarmMessageRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * Create a <code>cloudins_apm.alarm_message</code> table reference
     */
    public AlarmMessage() {
        this("alarm_message", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.alarm_message</code> table reference
     */
    public AlarmMessage(String alias) {
        this(alias, ALARM_MESSAGE);
    }

    private AlarmMessage(String alias, Table<AlarmMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlarmMessage(String alias, Table<AlarmMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AlarmMessageRecord, Long> getIdentity() {
        return Keys.IDENTITY_ALARM_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlarmMessageRecord> getPrimaryKey() {
        return Keys.KEY_ALARM_MESSAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlarmMessageRecord>> getKeys() {
        return Arrays.<UniqueKey<AlarmMessageRecord>>asList(Keys.KEY_ALARM_MESSAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlarmMessage as(String alias) {
        return new AlarmMessage(alias, this);
    }

    /**
     * Rename this table
     */
    public AlarmMessage rename(String name) {
        return new AlarmMessage(name, null);
    }
}
