/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.CloudinsSpanBaselineRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsSpanBaseline extends TableImpl<CloudinsSpanBaselineRecord> {

    private static final long serialVersionUID = 198410174;

    /**
     * The reference instance of <code>cloudins_apm.cloudins_span_baseline</code>
     */
    public static final CloudinsSpanBaseline CLOUDINS_SPAN_BASELINE = new CloudinsSpanBaseline();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CloudinsSpanBaselineRecord> getRecordType() {
        return CloudinsSpanBaselineRecord.class;
    }

    /**
     * The column <code>cloudins_apm.cloudins_span_baseline.trace_id</code>.
     */
    public final TableField<CloudinsSpanBaselineRecord, Long> TRACE_ID = createField("trace_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_span_baseline.id</code>.
     */
    public final TableField<CloudinsSpanBaselineRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_span_baseline.trace_md5</code>.
     */
    public final TableField<CloudinsSpanBaselineRecord, String> TRACE_MD5 = createField("trace_md5", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_span_baseline.name</code>.
     */
    public final TableField<CloudinsSpanBaselineRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_span_baseline.parent_id</code>.
     */
    public final TableField<CloudinsSpanBaselineRecord, Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>cloudins_apm.cloudins_span_baseline.start_ts</code>. Span.timestamp(): epoch micros used for endTs query and to implement TTL
     */
    public final TableField<CloudinsSpanBaselineRecord, Long> START_TS = createField("start_ts", org.jooq.impl.SQLDataType.BIGINT, this, "Span.timestamp(): epoch micros used for endTs query and to implement TTL");

    /**
     * The column <code>cloudins_apm.cloudins_span_baseline.duration</code>. Span.duration(): micros used for minDuration and maxDuration query
     */
    public final TableField<CloudinsSpanBaselineRecord, Long> DURATION = createField("duration", org.jooq.impl.SQLDataType.BIGINT, this, "Span.duration(): micros used for minDuration and maxDuration query");

    /**
     * Create a <code>cloudins_apm.cloudins_span_baseline</code> table reference
     */
    public CloudinsSpanBaseline() {
        this("cloudins_span_baseline", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.cloudins_span_baseline</code> table reference
     */
    public CloudinsSpanBaseline(String alias) {
        this(alias, CLOUDINS_SPAN_BASELINE);
    }

    private CloudinsSpanBaseline(String alias, Table<CloudinsSpanBaselineRecord> aliased) {
        this(alias, aliased, null);
    }

    private CloudinsSpanBaseline(String alias, Table<CloudinsSpanBaselineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CloudinsSpanBaselineRecord> getPrimaryKey() {
        return Keys.KEY_CLOUDINS_SPAN_BASELINE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CloudinsSpanBaselineRecord>> getKeys() {
        return Arrays.<UniqueKey<CloudinsSpanBaselineRecord>>asList(Keys.KEY_CLOUDINS_SPAN_BASELINE_PRIMARY, Keys.KEY_CLOUDINS_SPAN_BASELINE_TRACE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsSpanBaseline as(String alias) {
        return new CloudinsSpanBaseline(alias, this);
    }

    /**
     * Rename this table
     */
    public CloudinsSpanBaseline rename(String name) {
        return new CloudinsSpanBaseline(name, null);
    }
}
