/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.CloudinsUserRegionAppliRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsUserRegionAppli extends TableImpl<CloudinsUserRegionAppliRecord> {

    private static final long serialVersionUID = 13188982;

    /**
     * The reference instance of <code>cloudins_apm.cloudins_user_region_appli</code>
     */
    public static final CloudinsUserRegionAppli CLOUDINS_USER_REGION_APPLI = new CloudinsUserRegionAppli();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CloudinsUserRegionAppliRecord> getRecordType() {
        return CloudinsUserRegionAppliRecord.class;
    }

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.id</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.user_id</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.user_name</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.region_id</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, Long> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.region_name</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, String> REGION_NAME = createField("region_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.status</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.CHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.appli_msg</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, String> APPLI_MSG = createField("appli_msg", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user_region_appli.reply_msg</code>.
     */
    public final TableField<CloudinsUserRegionAppliRecord, String> REPLY_MSG = createField("reply_msg", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>cloudins_apm.cloudins_user_region_appli</code> table reference
     */
    public CloudinsUserRegionAppli() {
        this("cloudins_user_region_appli", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.cloudins_user_region_appli</code> table reference
     */
    public CloudinsUserRegionAppli(String alias) {
        this(alias, CLOUDINS_USER_REGION_APPLI);
    }

    private CloudinsUserRegionAppli(String alias, Table<CloudinsUserRegionAppliRecord> aliased) {
        this(alias, aliased, null);
    }

    private CloudinsUserRegionAppli(String alias, Table<CloudinsUserRegionAppliRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CloudinsUserRegionAppliRecord, Long> getIdentity() {
        return Keys.IDENTITY_CLOUDINS_USER_REGION_APPLI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CloudinsUserRegionAppliRecord> getPrimaryKey() {
        return Keys.KEY_CLOUDINS_USER_REGION_APPLI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CloudinsUserRegionAppliRecord>> getKeys() {
        return Arrays.<UniqueKey<CloudinsUserRegionAppliRecord>>asList(Keys.KEY_CLOUDINS_USER_REGION_APPLI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUserRegionAppli as(String alias) {
        return new CloudinsUserRegionAppli(alias, this);
    }

    /**
     * Rename this table
     */
    public CloudinsUserRegionAppli rename(String name) {
        return new CloudinsUserRegionAppli(name, null);
    }
}
