/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.CloudinsFieldRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsFieldTable extends TableImpl<CloudinsFieldRecord> {

    private static final long serialVersionUID = -663216013;

    /**
     * The reference instance of <code>cloudins.cloudins_field</code>
     */
    public static final CloudinsFieldTable CLOUDINS_FIELD = new CloudinsFieldTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CloudinsFieldRecord> getRecordType() {
        return CloudinsFieldRecord.class;
    }

    /**
     * The column <code>cloudins.cloudins_field.id</code>.
     */
    public final TableField<CloudinsFieldRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins.cloudins_field.name</code>.
     */
    public final TableField<CloudinsFieldRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_field.manager_id</code>.
     */
    public final TableField<CloudinsFieldRecord, Long> MANAGER_ID = createField("manager_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins.cloudins_field.manager_name</code>.
     */
    public final TableField<CloudinsFieldRecord, String> MANAGER_NAME = createField("manager_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_field.host_ip</code>.
     */
    public final TableField<CloudinsFieldRecord, String> HOST_IP = createField("host_ip", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_field.host_username</code>.
     */
    public final TableField<CloudinsFieldRecord, String> HOST_USERNAME = createField("host_username", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_field.host_password</code>.
     */
    public final TableField<CloudinsFieldRecord, String> HOST_PASSWORD = createField("host_password", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_field.company</code>.
     */
    public final TableField<CloudinsFieldRecord, String> COMPANY = createField("company", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_field.remark</code>.
     */
    public final TableField<CloudinsFieldRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>cloudins.cloudins_field</code> table reference
     */
    public CloudinsFieldTable() {
        this("cloudins_field", null);
    }

    /**
     * Create an aliased <code>cloudins.cloudins_field</code> table reference
     */
    public CloudinsFieldTable(String alias) {
        this(alias, CLOUDINS_FIELD);
    }

    private CloudinsFieldTable(String alias, Table<CloudinsFieldRecord> aliased) {
        this(alias, aliased, null);
    }

    private CloudinsFieldTable(String alias, Table<CloudinsFieldRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CloudinsFieldRecord, Long> getIdentity() {
        return Keys.IDENTITY_CLOUDINS_FIELD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CloudinsFieldRecord> getPrimaryKey() {
        return Keys.KEY_CLOUDINS_FIELD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CloudinsFieldRecord>> getKeys() {
        return Arrays.<UniqueKey<CloudinsFieldRecord>>asList(Keys.KEY_CLOUDINS_FIELD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsFieldTable as(String alias) {
        return new CloudinsFieldTable(alias, this);
    }

    /**
     * Rename this table
     */
    public CloudinsFieldTable rename(String name) {
        return new CloudinsFieldTable(name, null);
    }
}
