/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.CloudinsLogRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsLog extends TableImpl<CloudinsLogRecord> {

    private static final long serialVersionUID = 144670130;

    /**
     * The reference instance of <code>cloudins.cloudins_log</code>
     */
    public static final CloudinsLog CLOUDINS_LOG = new CloudinsLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CloudinsLogRecord> getRecordType() {
        return CloudinsLogRecord.class;
    }

    /**
     * The column <code>cloudins.cloudins_log.id</code>.
     */
    public final TableField<CloudinsLogRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins.cloudins_log.level</code>.
     */
    public final TableField<CloudinsLogRecord, String> LEVEL = createField("level", org.jooq.impl.SQLDataType.CHAR.length(10).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_log.method</code>.
     */
    public final TableField<CloudinsLogRecord, String> METHOD = createField("method", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.cloudins_log.message</code>.
     */
    public final TableField<CloudinsLogRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cloudins.cloudins_log.time</code>.
     */
    public final TableField<CloudinsLogRecord, String> TIME = createField("time", org.jooq.impl.SQLDataType.CHAR.length(20), this, "");

    /**
     * The column <code>cloudins.cloudins_log.line</code>.
     */
    public final TableField<CloudinsLogRecord, Integer> LINE = createField("line", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>cloudins.cloudins_log.displayed</code>.
     */
    public final TableField<CloudinsLogRecord, Boolean> DISPLAYED = createField("displayed", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>cloudins.cloudins_log.isread</code>.
     */
    public final TableField<CloudinsLogRecord, Boolean> ISREAD = createField("isread", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>cloudins.cloudins_log</code> table reference
     */
    public CloudinsLog() {
        this("cloudins_log", null);
    }

    /**
     * Create an aliased <code>cloudins.cloudins_log</code> table reference
     */
    public CloudinsLog(String alias) {
        this(alias, CLOUDINS_LOG);
    }

    private CloudinsLog(String alias, Table<CloudinsLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private CloudinsLog(String alias, Table<CloudinsLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CloudinsLogRecord, Long> getIdentity() {
        return Keys.IDENTITY_CLOUDINS_LOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CloudinsLogRecord> getPrimaryKey() {
        return Keys.KEY_CLOUDINS_LOG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CloudinsLogRecord>> getKeys() {
        return Arrays.<UniqueKey<CloudinsLogRecord>>asList(Keys.KEY_CLOUDINS_LOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsLog as(String alias) {
        return new CloudinsLog(alias, this);
    }

    /**
     * Rename this table
     */
    public CloudinsLog rename(String name) {
        return new CloudinsLog(name, null);
    }
}
