/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.CloudinsConfigRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsConfig extends TableImpl<CloudinsConfigRecord> {

    private static final long serialVersionUID = -811014143;

    /**
     * The reference instance of <code>cloudins_apm.cloudins_config</code>
     */
    public static final CloudinsConfig CLOUDINS_CONFIG = new CloudinsConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CloudinsConfigRecord> getRecordType() {
        return CloudinsConfigRecord.class;
    }

    /**
     * The column <code>cloudins_apm.cloudins_config.id</code>.
     */
    public final TableField<CloudinsConfigRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_config.product</code>. cloudins产品名称，如generater、analyzer等
     */
    public final TableField<CloudinsConfigRecord, String> PRODUCT = createField("product", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "cloudins产品名称，如generater、analyzer等");

    /**
     * The column <code>cloudins_apm.cloudins_config.module</code>. config中的分类，如db, parameter,connection等
     */
    public final TableField<CloudinsConfigRecord, String> MODULE = createField("module", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "config中的分类，如db, parameter,connection等");

    /**
     * The column <code>cloudins_apm.cloudins_config.parm_alias</code>.
     */
    public final TableField<CloudinsConfigRecord, String> PARM_ALIAS = createField("parm_alias", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_config.parm_name</code>.
     */
    public final TableField<CloudinsConfigRecord, String> PARM_NAME = createField("parm_name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_config.parm_value</code>.
     */
    public final TableField<CloudinsConfigRecord, String> PARM_VALUE = createField("parm_value", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_config.flag</code>. 预留字段
     */
    public final TableField<CloudinsConfigRecord, Integer> FLAG = createField("flag", org.jooq.impl.SQLDataType.INTEGER, this, "预留字段");

    /**
     * The column <code>cloudins_apm.cloudins_config.comment</code>.
     */
    public final TableField<CloudinsConfigRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * Create a <code>cloudins_apm.cloudins_config</code> table reference
     */
    public CloudinsConfig() {
        this("cloudins_config", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.cloudins_config</code> table reference
     */
    public CloudinsConfig(String alias) {
        this(alias, CLOUDINS_CONFIG);
    }

    private CloudinsConfig(String alias, Table<CloudinsConfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private CloudinsConfig(String alias, Table<CloudinsConfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CloudinsConfigRecord> getPrimaryKey() {
        return Keys.KEY_CLOUDINS_CONFIG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CloudinsConfigRecord>> getKeys() {
        return Arrays.<UniqueKey<CloudinsConfigRecord>>asList(Keys.KEY_CLOUDINS_CONFIG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsConfig as(String alias) {
        return new CloudinsConfig(alias, this);
    }

    /**
     * Rename this table
     */
    public CloudinsConfig rename(String name) {
        return new CloudinsConfig(name, null);
    }
}
