/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.CloudinsUserRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsUser extends TableImpl<CloudinsUserRecord> {

    private static final long serialVersionUID = -1548199042;

    /**
     * The reference instance of <code>cloudins_apm.cloudins_user</code>
     */
    public static final CloudinsUser CLOUDINS_USER = new CloudinsUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CloudinsUserRecord> getRecordType() {
        return CloudinsUserRecord.class;
    }

    /**
     * The column <code>cloudins_apm.cloudins_user.id</code>.
     */
    public final TableField<CloudinsUserRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.role_id</code>.
     */
    public final TableField<CloudinsUserRecord, Long> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.region_id</code>.
     */
    public final TableField<CloudinsUserRecord, Long> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.account</code>.
     */
    public final TableField<CloudinsUserRecord, String> ACCOUNT = createField("account", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.name</code>.
     */
    public final TableField<CloudinsUserRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.password</code>.
     */
    public final TableField<CloudinsUserRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.gender</code>.
     */
    public final TableField<CloudinsUserRecord, Boolean> GENDER = createField("gender", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.mail</code>.
     */
    public final TableField<CloudinsUserRecord, String> MAIL = createField("mail", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.company</code>.
     */
    public final TableField<CloudinsUserRecord, String> COMPANY = createField("company", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.phone</code>.
     */
    public final TableField<CloudinsUserRecord, Long> PHONE = createField("phone", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.qq</code>.
     */
    public final TableField<CloudinsUserRecord, Long> QQ = createField("qq", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.status</code>.
     */
    public final TableField<CloudinsUserRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.cloudins_user.remark</code>.
     */
    public final TableField<CloudinsUserRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>cloudins_apm.cloudins_user</code> table reference
     */
    public CloudinsUser() {
        this("cloudins_user", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.cloudins_user</code> table reference
     */
    public CloudinsUser(String alias) {
        this(alias, CLOUDINS_USER);
    }

    private CloudinsUser(String alias, Table<CloudinsUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private CloudinsUser(String alias, Table<CloudinsUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CloudinsUserRecord, Long> getIdentity() {
        return Keys.IDENTITY_CLOUDINS_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CloudinsUserRecord> getPrimaryKey() {
        return Keys.KEY_CLOUDINS_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CloudinsUserRecord>> getKeys() {
        return Arrays.<UniqueKey<CloudinsUserRecord>>asList(Keys.KEY_CLOUDINS_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CloudinsUser as(String alias) {
        return new CloudinsUser(alias, this);
    }

    /**
     * Rename this table
     */
    public CloudinsUser rename(String name) {
        return new CloudinsUser(name, null);
    }
}
