/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.JobSummaryBasicRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobSummaryBasic extends TableImpl<JobSummaryBasicRecord> {

    private static final long serialVersionUID = -1853951697;

    /**
     * The reference instance of <code>cloudins.job_summary_basic</code>
     */
    public static final JobSummaryBasic JOB_SUMMARY_BASIC = new JobSummaryBasic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobSummaryBasicRecord> getRecordType() {
        return JobSummaryBasicRecord.class;
    }

    /**
     * The column <code>cloudins.job_summary_basic.id</code>.
     */
    public final TableField<JobSummaryBasicRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.summary_date</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> SUMMARY_DATE = createField("summary_date", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.start_time</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.last_update_time</code>. 默认每小时生成一条新纪录，每分钟更新当前记录数据
     */
    public final TableField<JobSummaryBasicRecord, String> LAST_UPDATE_TIME = createField("last_update_time", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "默认每小时生成一条新纪录，每分钟更新当前记录数据");

    /**
     * The column <code>cloudins.job_summary_basic.job_total_num</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> JOB_TOTAL_NUM = createField("job_total_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.job_critical_num</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> JOB_CRITICAL_NUM = createField("job_critical_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.job_severe_num</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> JOB_SEVERE_NUM = createField("job_severe_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.job_moderate_num</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> JOB_MODERATE_NUM = createField("job_moderate_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.job_normal_num</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> JOB_NORMAL_NUM = createField("job_normal_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.job_type_num</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> JOB_TYPE_NUM = createField("job_type_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.job_summary_basic.user_num</code>.
     */
    public final TableField<JobSummaryBasicRecord, String> USER_NUM = createField("user_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * Create a <code>cloudins.job_summary_basic</code> table reference
     */
    public JobSummaryBasic() {
        this("job_summary_basic", null);
    }

    /**
     * Create an aliased <code>cloudins.job_summary_basic</code> table reference
     */
    public JobSummaryBasic(String alias) {
        this(alias, JOB_SUMMARY_BASIC);
    }

    private JobSummaryBasic(String alias, Table<JobSummaryBasicRecord> aliased) {
        this(alias, aliased, null);
    }

    private JobSummaryBasic(String alias, Table<JobSummaryBasicRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JobSummaryBasicRecord> getPrimaryKey() {
        return Keys.KEY_JOB_SUMMARY_BASIC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JobSummaryBasicRecord>> getKeys() {
        return Arrays.<UniqueKey<JobSummaryBasicRecord>>asList(Keys.KEY_JOB_SUMMARY_BASIC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobSummaryBasic as(String alias) {
        return new JobSummaryBasic(alias, this);
    }

    /**
     * Rename this table
     */
    public JobSummaryBasic rename(String name) {
        return new JobSummaryBasic(name, null);
    }
}
