/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.SpanInfosRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpanInfos extends TableImpl<SpanInfosRecord> {

    private static final long serialVersionUID = -1590144214;

    /**
     * The reference instance of <code>cloudins_apm.span_infos</code>
     */
    public static final SpanInfos SPAN_INFOS = new SpanInfos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpanInfosRecord> getRecordType() {
        return SpanInfosRecord.class;
    }

    /**
     * The column <code>cloudins_apm.span_infos.name</code>.
     */
    public final TableField<SpanInfosRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.span_infos.alias</code>.
     */
    public final TableField<SpanInfosRecord, String> ALIAS = createField("alias", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.span_infos.def_baseline</code>.
     */
    public final TableField<SpanInfosRecord, String> DEF_BASELINE = createField("def_baseline", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.span_infos.cust_baseline</code>.
     */
    public final TableField<SpanInfosRecord, String> CUST_BASELINE = createField("cust_baseline", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>cloudins_apm.span_infos</code> table reference
     */
    public SpanInfos() {
        this("span_infos", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.span_infos</code> table reference
     */
    public SpanInfos(String alias) {
        this(alias, SPAN_INFOS);
    }

    private SpanInfos(String alias, Table<SpanInfosRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpanInfos(String alias, Table<SpanInfosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SpanInfosRecord> getPrimaryKey() {
        return Keys.KEY_SPAN_INFOS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SpanInfosRecord>> getKeys() {
        return Arrays.<UniqueKey<SpanInfosRecord>>asList(Keys.KEY_SPAN_INFOS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpanInfos as(String alias) {
        return new SpanInfos(alias, this);
    }

    /**
     * Rename this table
     */
    public SpanInfos rename(String name) {
        return new SpanInfos(name, null);
    }
}
