/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.SysConfigsRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysConfigs extends TableImpl<SysConfigsRecord> {

    private static final long serialVersionUID = -1206608372;

    /**
     * The reference instance of <code>cloudins.sys_configs</code>
     */
    public static final SysConfigs SYS_CONFIGS = new SysConfigs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysConfigsRecord> getRecordType() {
        return SysConfigsRecord.class;
    }

    /**
     * The column <code>cloudins.sys_configs.config_name</code>.
     */
    public final TableField<SysConfigsRecord, String> CONFIG_NAME = createField("config_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>cloudins.sys_configs.config_value</code>.
     */
    public final TableField<SysConfigsRecord, String> CONFIG_VALUE = createField("config_value", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>cloudins.sys_configs</code> table reference
     */
    public SysConfigs() {
        this("sys_configs", null);
    }

    /**
     * Create an aliased <code>cloudins.sys_configs</code> table reference
     */
    public SysConfigs(String alias) {
        this(alias, SYS_CONFIGS);
    }

    private SysConfigs(String alias, Table<SysConfigsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysConfigs(String alias, Table<SysConfigsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysConfigsRecord> getPrimaryKey() {
        return Keys.KEY_SYS_CONFIGS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysConfigsRecord>> getKeys() {
        return Arrays.<UniqueKey<SysConfigsRecord>>asList(Keys.KEY_SYS_CONFIGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysConfigs as(String alias) {
        return new SysConfigs(alias, this);
    }

    /**
     * Rename this table
     */
    public SysConfigs rename(String name) {
        return new SysConfigs(name, null);
    }
}
