/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.TracesRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Traces extends TableImpl<TracesRecord> {

    private static final long serialVersionUID = -750790185;

    /**
     * The reference instance of <code>cloudins_apm.traces</code>
     */
    public static final Traces TRACES = new Traces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TracesRecord> getRecordType() {
        return TracesRecord.class;
    }

    /**
     * The column <code>cloudins_apm.traces.trace_id</code>.
     */
    public final TableField<TracesRecord, Long> TRACE_ID = createField("trace_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.traces.trace_md5</code>.
     */
    public final TableField<TracesRecord, String> TRACE_MD5 = createField("trace_md5", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.traces.start_ts</code>.
     */
    public final TableField<TracesRecord, Long> START_TS = createField("start_ts", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.traces.record_ts</code>.
     */
    public final TableField<TracesRecord, Long> RECORD_TS = createField("record_ts", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.traces.duration</code>.
     */
    public final TableField<TracesRecord, Long> DURATION = createField("duration", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.traces.end_ts</code>.
     */
    public final TableField<TracesRecord, Long> END_TS = createField("end_ts", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.traces.team_code</code>.
     */
    public final TableField<TracesRecord, Short> TEAM_CODE = createField("team_code", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * Create a <code>cloudins_apm.traces</code> table reference
     */
    public Traces() {
        this("traces", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.traces</code> table reference
     */
    public Traces(String alias) {
        this(alias, TRACES);
    }

    private Traces(String alias, Table<TracesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Traces(String alias, Table<TracesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TracesRecord> getPrimaryKey() {
        return Keys.KEY_TRACES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TracesRecord>> getKeys() {
        return Arrays.<UniqueKey<TracesRecord>>asList(Keys.KEY_TRACES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Traces as(String alias) {
        return new Traces(alias, this);
    }

    /**
     * Rename this table
     */
    public Traces rename(String name) {
        return new Traces(name, null);
    }
}
