/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.CloudinsApm;
import jooq.data.Keys;
import jooq.data.tables.records.TraceInfosRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraceInfos extends TableImpl<TraceInfosRecord> {

    private static final long serialVersionUID = 861302266;

    /**
     * The reference instance of <code>cloudins_apm.trace_infos</code>
     */
    public static final TraceInfos TRACE_INFOS = new TraceInfos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TraceInfosRecord> getRecordType() {
        return TraceInfosRecord.class;
    }

    /**
     * The column <code>cloudins_apm.trace_infos.trace_md5</code>.
     */
    public final TableField<TraceInfosRecord, String> TRACE_MD5 = createField("trace_md5", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.trace_infos.root_name</code>.
     */
    public final TableField<TraceInfosRecord, String> ROOT_NAME = createField("root_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.trace_infos.trace_name</code>.
     */
    public final TableField<TraceInfosRecord, String> TRACE_NAME = createField("trace_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.trace_infos.span_count</code>.
     */
    public final TableField<TraceInfosRecord, Short> SPAN_COUNT = createField("span_count", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>cloudins_apm.trace_infos.trace_alias</code>.
     */
    public final TableField<TraceInfosRecord, String> TRACE_ALIAS = createField("trace_alias", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins_apm.trace_infos.base_trace_id</code>.
     */
    public final TableField<TraceInfosRecord, Long> BASE_TRACE_ID = createField("base_trace_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins_apm.trace_infos.warning_duration</code>. 固定时长
     */
    public final TableField<TraceInfosRecord, Long> WARNING_DURATION = createField("warning_duration", org.jooq.impl.SQLDataType.BIGINT, this, "固定时长");

    /**
     * The column <code>cloudins_apm.trace_infos.warning_percentage</code>. 超出基线百分比
     */
    public final TableField<TraceInfosRecord, Integer> WARNING_PERCENTAGE = createField("warning_percentage", org.jooq.impl.SQLDataType.INTEGER, this, "超出基线百分比");

    /**
     * The column <code>cloudins_apm.trace_infos.duration</code>.
     */
    public final TableField<TraceInfosRecord, Long> DURATION = createField("duration", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>cloudins_apm.trace_infos</code> table reference
     */
    public TraceInfos() {
        this("trace_infos", null);
    }

    /**
     * Create an aliased <code>cloudins_apm.trace_infos</code> table reference
     */
    public TraceInfos(String alias) {
        this(alias, TRACE_INFOS);
    }

    private TraceInfos(String alias, Table<TraceInfosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TraceInfos(String alias, Table<TraceInfosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CloudinsApm.CLOUDINS_APM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TraceInfosRecord> getPrimaryKey() {
        return Keys.KEY_TRACE_INFOS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TraceInfosRecord>> getKeys() {
        return Arrays.<UniqueKey<TraceInfosRecord>>asList(Keys.KEY_TRACE_INFOS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceInfos as(String alias) {
        return new TraceInfos(alias, this);
    }

    /**
     * Rename this table
     */
    public TraceInfos rename(String name) {
        return new TraceInfos(name, null);
    }
}
