/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.UserJobSummaryRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserJobSummary extends TableImpl<UserJobSummaryRecord> {

    private static final long serialVersionUID = 859437525;

    /**
     * The reference instance of <code>cloudins.user_job_summary</code>
     */
    public static final UserJobSummary USER_JOB_SUMMARY = new UserJobSummary();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserJobSummaryRecord> getRecordType() {
        return UserJobSummaryRecord.class;
    }

    /**
     * The column <code>cloudins.user_job_summary.id</code>.
     */
    public final TableField<UserJobSummaryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cloudins.user_job_summary.job_summary_basic_id</code>.
     */
    public final TableField<UserJobSummaryRecord, Integer> JOB_SUMMARY_BASIC_ID = createField("job_summary_basic_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cloudins.user_job_summary.username</code>.
     */
    public final TableField<UserJobSummaryRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.user_job_summary.job_type_num</code>.
     */
    public final TableField<UserJobSummaryRecord, String> JOB_TYPE_NUM = createField("job_type_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.user_job_summary.job_total_num</code>. 该条记录时间周期内，该job type下的job数量
     */
    public final TableField<UserJobSummaryRecord, String> JOB_TOTAL_NUM = createField("job_total_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "该条记录时间周期内，该job type下的job数量");

    /**
     * The column <code>cloudins.user_job_summary.job_critical_num</code>.
     */
    public final TableField<UserJobSummaryRecord, String> JOB_CRITICAL_NUM = createField("job_critical_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.user_job_summary.job_severe_num</code>.
     */
    public final TableField<UserJobSummaryRecord, String> JOB_SEVERE_NUM = createField("job_severe_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.user_job_summary.job_moderate_num</code>.
     */
    public final TableField<UserJobSummaryRecord, String> JOB_MODERATE_NUM = createField("job_moderate_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cloudins.user_job_summary.job_normal_num</code>.
     */
    public final TableField<UserJobSummaryRecord, String> JOB_NORMAL_NUM = createField("job_normal_num", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * Create a <code>cloudins.user_job_summary</code> table reference
     */
    public UserJobSummary() {
        this("user_job_summary", null);
    }

    /**
     * Create an aliased <code>cloudins.user_job_summary</code> table reference
     */
    public UserJobSummary(String alias) {
        this(alias, USER_JOB_SUMMARY);
    }

    private UserJobSummary(String alias, Table<UserJobSummaryRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserJobSummary(String alias, Table<UserJobSummaryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserJobSummaryRecord> getPrimaryKey() {
        return Keys.KEY_USER_JOB_SUMMARY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserJobSummaryRecord>> getKeys() {
        return Arrays.<UniqueKey<UserJobSummaryRecord>>asList(Keys.KEY_USER_JOB_SUMMARY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserJobSummaryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserJobSummaryRecord, ?>>asList(Keys.FK_USER_JOB_SUMMARY_JOB_SUMMARY_BASIC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobSummary as(String alias) {
        return new UserJobSummary(alias, this);
    }

    /**
     * Rename this table
     */
    public UserJobSummary rename(String name) {
        return new UserJobSummary(name, null);
    }
}
