/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.YarnAppHeuristicResultRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppHeuristicResult extends TableImpl<YarnAppHeuristicResultRecord> {

    private static final long serialVersionUID = -826825123;

    /**
     * The reference instance of <code>cloudins.yarn_app_heuristic_result</code>
     */
    public static final YarnAppHeuristicResult YARN_APP_HEURISTIC_RESULT = new YarnAppHeuristicResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YarnAppHeuristicResultRecord> getRecordType() {
        return YarnAppHeuristicResultRecord.class;
    }

    /**
     * The column <code>cloudins.yarn_app_heuristic_result.id</code>. The application heuristic result id
     */
    public final TableField<YarnAppHeuristicResultRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "The application heuristic result id");

    /**
     * The column <code>cloudins.yarn_app_heuristic_result.yarn_app_result_id</code>. The application id
     */
    public final TableField<YarnAppHeuristicResultRecord, String> YARN_APP_RESULT_ID = createField("yarn_app_result_id", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "The application id");

    /**
     * The column <code>cloudins.yarn_app_heuristic_result.heuristic_class</code>. Name of the JVM class that implements this heuristic
     */
    public final TableField<YarnAppHeuristicResultRecord, String> HEURISTIC_CLASS = createField("heuristic_class", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "Name of the JVM class that implements this heuristic");

    /**
     * The column <code>cloudins.yarn_app_heuristic_result.heuristic_name</code>. The heuristic name
     */
    public final TableField<YarnAppHeuristicResultRecord, String> HEURISTIC_NAME = createField("heuristic_name", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "The heuristic name");

    /**
     * The column <code>cloudins.yarn_app_heuristic_result.severity</code>. The heuristic severity ranging from 0(LOW) to 4(CRITICAL)
     */
    public final TableField<YarnAppHeuristicResultRecord, Boolean> SEVERITY = createField("severity", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "The heuristic severity ranging from 0(LOW) to 4(CRITICAL)");

    /**
     * The column <code>cloudins.yarn_app_heuristic_result.score</code>. The heuristic score for the application. score = severity * number_of_tasks(map/reduce) where severity not in [0,1], otherwise score = 0
     */
    public final TableField<YarnAppHeuristicResultRecord, UInteger> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "The heuristic score for the application. score = severity * number_of_tasks(map/reduce) where severity not in [0,1], otherwise score = 0");

    /**
     * Create a <code>cloudins.yarn_app_heuristic_result</code> table reference
     */
    public YarnAppHeuristicResult() {
        this("yarn_app_heuristic_result", null);
    }

    /**
     * Create an aliased <code>cloudins.yarn_app_heuristic_result</code> table reference
     */
    public YarnAppHeuristicResult(String alias) {
        this(alias, YARN_APP_HEURISTIC_RESULT);
    }

    private YarnAppHeuristicResult(String alias, Table<YarnAppHeuristicResultRecord> aliased) {
        this(alias, aliased, null);
    }

    private YarnAppHeuristicResult(String alias, Table<YarnAppHeuristicResultRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<YarnAppHeuristicResultRecord, Integer> getIdentity() {
        return Keys.IDENTITY_YARN_APP_HEURISTIC_RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<YarnAppHeuristicResultRecord> getPrimaryKey() {
        return Keys.KEY_YARN_APP_HEURISTIC_RESULT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<YarnAppHeuristicResultRecord>> getKeys() {
        return Arrays.<UniqueKey<YarnAppHeuristicResultRecord>>asList(Keys.KEY_YARN_APP_HEURISTIC_RESULT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<YarnAppHeuristicResultRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<YarnAppHeuristicResultRecord, ?>>asList(Keys.YARN_APP_HEURISTIC_RESULT_F1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppHeuristicResult as(String alias) {
        return new YarnAppHeuristicResult(alias, this);
    }

    /**
     * Rename this table
     */
    public YarnAppHeuristicResult rename(String name) {
        return new YarnAppHeuristicResult(name, null);
    }
}
