/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.YarnAppCheckSettingRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppCheckSetting extends TableImpl<YarnAppCheckSettingRecord> {

    private static final long serialVersionUID = -614320640;

    /**
     * The reference instance of <code>cloudins.yarn_app_check_setting</code>
     */
    public static final YarnAppCheckSetting YARN_APP_CHECK_SETTING = new YarnAppCheckSetting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YarnAppCheckSettingRecord> getRecordType() {
        return YarnAppCheckSettingRecord.class;
    }

    /**
     * The column <code>cloudins.yarn_app_check_setting.id</code>.
     */
    public final TableField<YarnAppCheckSettingRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>cloudins.yarn_app_check_setting.name</code>.
     */
    public final TableField<YarnAppCheckSettingRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("NAN", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>cloudins.yarn_app_check_setting.type</code>.
     */
    public final TableField<YarnAppCheckSettingRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>cloudins.yarn_app_check_setting.duration</code>.
     */
    public final TableField<YarnAppCheckSettingRecord, Long> DURATION = createField("duration", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>cloudins.yarn_app_check_setting.score</code>.
     */
    public final TableField<YarnAppCheckSettingRecord, Integer> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>cloudins.yarn_app_check_setting.severity</code>.
     */
    public final TableField<YarnAppCheckSettingRecord, Boolean> SEVERITY = createField("severity", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>cloudins.yarn_app_check_setting</code> table reference
     */
    public YarnAppCheckSetting() {
        this("yarn_app_check_setting", null);
    }

    /**
     * Create an aliased <code>cloudins.yarn_app_check_setting</code> table reference
     */
    public YarnAppCheckSetting(String alias) {
        this(alias, YARN_APP_CHECK_SETTING);
    }

    private YarnAppCheckSetting(String alias, Table<YarnAppCheckSettingRecord> aliased) {
        this(alias, aliased, null);
    }

    private YarnAppCheckSetting(String alias, Table<YarnAppCheckSettingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<YarnAppCheckSettingRecord, Long> getIdentity() {
        return Keys.IDENTITY_YARN_APP_CHECK_SETTING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<YarnAppCheckSettingRecord> getPrimaryKey() {
        return Keys.KEY_YARN_APP_CHECK_SETTING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<YarnAppCheckSettingRecord>> getKeys() {
        return Arrays.<UniqueKey<YarnAppCheckSettingRecord>>asList(Keys.KEY_YARN_APP_CHECK_SETTING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppCheckSetting as(String alias) {
        return new YarnAppCheckSetting(alias, this);
    }

    /**
     * Rename this table
     */
    public YarnAppCheckSetting rename(String name) {
        return new YarnAppCheckSetting(name, null);
    }
}
