/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.YarnAppResultRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppResult extends TableImpl<YarnAppResultRecord> {

    private static final long serialVersionUID = -1292707888;

    /**
     * The reference instance of <code>cloudins.yarn_app_result</code>
     */
    public static final YarnAppResult YARN_APP_RESULT = new YarnAppResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YarnAppResultRecord> getRecordType() {
        return YarnAppResultRecord.class;
    }

    /**
     * The column <code>cloudins.yarn_app_result.id</code>. The application id, e.g., application_1236543456321_1234567
     */
    public final TableField<YarnAppResultRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "The application id, e.g., application_1236543456321_1234567");

    /**
     * The column <code>cloudins.yarn_app_result.name</code>. The application name
     */
    public final TableField<YarnAppResultRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "The application name");

    /**
     * The column <code>cloudins.yarn_app_result.username</code>. The user who started the application
     */
    public final TableField<YarnAppResultRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "The user who started the application");

    /**
     * The column <code>cloudins.yarn_app_result.queue_name</code>. The queue the application was submitted to
     */
    public final TableField<YarnAppResultRecord, String> QUEUE_NAME = createField("queue_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "The queue the application was submitted to");

    /**
     * The column <code>cloudins.yarn_app_result.start_time</code>. The time in which application started
     */
    public final TableField<YarnAppResultRecord, ULong> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "The time in which application started");

    /**
     * The column <code>cloudins.yarn_app_result.finish_time</code>. The time in which application finished
     */
    public final TableField<YarnAppResultRecord, ULong> FINISH_TIME = createField("finish_time", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "The time in which application finished");

    /**
     * The column <code>cloudins.yarn_app_result.record_ts</code>.
     */
    public final TableField<YarnAppResultRecord, Long> RECORD_TS = createField("record_ts", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>cloudins.yarn_app_result.tracking_url</code>. The web URL that can be used to track the application
     */
    public final TableField<YarnAppResultRecord, String> TRACKING_URL = createField("tracking_url", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "The web URL that can be used to track the application");

    /**
     * The column <code>cloudins.yarn_app_result.job_type</code>. The Job Type e.g, Pig, Hive, Spark, HadoopJava
     */
    public final TableField<YarnAppResultRecord, String> JOB_TYPE = createField("job_type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "The Job Type e.g, Pig, Hive, Spark, HadoopJava");

    /**
     * The column <code>cloudins.yarn_app_result.severity</code>. Aggregate severity of all the heuristics. Ranges from 0(LOW) to 4(CRITICAL)
     */
    public final TableField<YarnAppResultRecord, Boolean> SEVERITY = createField("severity", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "Aggregate severity of all the heuristics. Ranges from 0(LOW) to 4(CRITICAL)");

    /**
     * The column <code>cloudins.yarn_app_result.score</code>. The application score which is the sum of heuristic scores
     */
    public final TableField<YarnAppResultRecord, UInteger> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "The application score which is the sum of heuristic scores");

    /**
     * The column <code>cloudins.yarn_app_result.workflow_depth</code>. The application depth in the scheduled flow. Depth starts from 0
     */
    public final TableField<YarnAppResultRecord, Boolean> WORKFLOW_DEPTH = createField("workflow_depth", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "The application depth in the scheduled flow. Depth starts from 0");

    /**
     * The column <code>cloudins.yarn_app_result.scheduler</code>. The scheduler which triggered the application
     */
    public final TableField<YarnAppResultRecord, String> SCHEDULER = createField("scheduler", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "The scheduler which triggered the application");

    /**
     * The column <code>cloudins.yarn_app_result.job_name</code>. The name of the job in the flow to which this app belongs
     */
    public final TableField<YarnAppResultRecord, String> JOB_NAME = createField("job_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "The name of the job in the flow to which this app belongs");

    /**
     * The column <code>cloudins.yarn_app_result.job_exec_id</code>. A unique reference to a specific execution of the job/action(job in the workflow). This should filter all applications (mapreduce/spark) triggered by the job for a particular execution.
     */
    public final TableField<YarnAppResultRecord, String> JOB_EXEC_ID = createField("job_exec_id", org.jooq.impl.SQLDataType.VARCHAR.length(800).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A unique reference to a specific execution of the job/action(job in the workflow). This should filter all applications (mapreduce/spark) triggered by the job for a particular execution.");

    /**
     * The column <code>cloudins.yarn_app_result.flow_exec_id</code>. A unique reference to a specific flow execution. This should filter all applications fired by a particular flow execution. Note that if the scheduler supports sub-workflows, then this ID should be the super parent flow execution id that triggered the the applications and sub-workflows.
     */
    public final TableField<YarnAppResultRecord, String> FLOW_EXEC_ID = createField("flow_exec_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A unique reference to a specific flow execution. This should filter all applications fired by a particular flow execution. Note that if the scheduler supports sub-workflows, then this ID should be the super parent flow execution id that triggered the the applications and sub-workflows.");

    /**
     * The column <code>cloudins.yarn_app_result.job_def_id</code>. A unique reference to the job in the entire flow independent of the execution. This should filter all the applications(mapreduce/spark) triggered by the job for all the historic executions of that job.
     */
    public final TableField<YarnAppResultRecord, String> JOB_DEF_ID = createField("job_def_id", org.jooq.impl.SQLDataType.VARCHAR.length(800).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A unique reference to the job in the entire flow independent of the execution. This should filter all the applications(mapreduce/spark) triggered by the job for all the historic executions of that job.");

    /**
     * The column <code>cloudins.yarn_app_result.flow_def_id</code>. A unique reference to the entire flow independent of any execution. This should filter all the historic mr jobs belonging to the flow. Note that if your scheduler supports sub-workflows, then this ID should reference the super parent flow that triggered the all the jobs and sub-workflows.
     */
    public final TableField<YarnAppResultRecord, String> FLOW_DEF_ID = createField("flow_def_id", org.jooq.impl.SQLDataType.VARCHAR.length(800).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A unique reference to the entire flow independent of any execution. This should filter all the historic mr jobs belonging to the flow. Note that if your scheduler supports sub-workflows, then this ID should reference the super parent flow that triggered the all the jobs and sub-workflows.");

    /**
     * The column <code>cloudins.yarn_app_result.job_exec_url</code>. A url to the job execution on the scheduler
     */
    public final TableField<YarnAppResultRecord, String> JOB_EXEC_URL = createField("job_exec_url", org.jooq.impl.SQLDataType.VARCHAR.length(800).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A url to the job execution on the scheduler");

    /**
     * The column <code>cloudins.yarn_app_result.flow_exec_url</code>. A url to the flow execution on the scheduler
     */
    public final TableField<YarnAppResultRecord, String> FLOW_EXEC_URL = createField("flow_exec_url", org.jooq.impl.SQLDataType.VARCHAR.length(800).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A url to the flow execution on the scheduler");

    /**
     * The column <code>cloudins.yarn_app_result.job_def_url</code>. A url to the job definition on the scheduler
     */
    public final TableField<YarnAppResultRecord, String> JOB_DEF_URL = createField("job_def_url", org.jooq.impl.SQLDataType.VARCHAR.length(800).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A url to the job definition on the scheduler");

    /**
     * The column <code>cloudins.yarn_app_result.flow_def_url</code>. A url to the flow definition on the scheduler
     */
    public final TableField<YarnAppResultRecord, String> FLOW_DEF_URL = createField("flow_def_url", org.jooq.impl.SQLDataType.VARCHAR.length(800).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "A url to the flow definition on the scheduler");

    /**
     * Create a <code>cloudins.yarn_app_result</code> table reference
     */
    public YarnAppResult() {
        this("yarn_app_result", null);
    }

    /**
     * Create an aliased <code>cloudins.yarn_app_result</code> table reference
     */
    public YarnAppResult(String alias) {
        this(alias, YARN_APP_RESULT);
    }

    private YarnAppResult(String alias, Table<YarnAppResultRecord> aliased) {
        this(alias, aliased, null);
    }

    private YarnAppResult(String alias, Table<YarnAppResultRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<YarnAppResultRecord> getPrimaryKey() {
        return Keys.KEY_YARN_APP_RESULT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<YarnAppResultRecord>> getKeys() {
        return Arrays.<UniqueKey<YarnAppResultRecord>>asList(Keys.KEY_YARN_APP_RESULT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YarnAppResult as(String alias) {
        return new YarnAppResult(alias, this);
    }

    /**
     * Rename this table
     */
    public YarnAppResult rename(String name) {
        return new YarnAppResult(name, null);
    }
}
