/**
 * This class is generated by jOOQ
 */
package jooq.data.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.Cloudins;
import jooq.data.Keys;
import jooq.data.tables.records.ZipkinDependenciesRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZipkinDependencies extends TableImpl<ZipkinDependenciesRecord> {

    private static final long serialVersionUID = 325766298;

    /**
     * The reference instance of <code>cloudins.zipkin_dependencies</code>
     */
    public static final ZipkinDependencies ZIPKIN_DEPENDENCIES = new ZipkinDependencies();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ZipkinDependenciesRecord> getRecordType() {
        return ZipkinDependenciesRecord.class;
    }

    /**
     * The column <code>cloudins.zipkin_dependencies.day</code>.
     */
    public final TableField<ZipkinDependenciesRecord, Date> DAY = createField("day", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>cloudins.zipkin_dependencies.parent</code>.
     */
    public final TableField<ZipkinDependenciesRecord, String> PARENT = createField("parent", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>cloudins.zipkin_dependencies.child</code>.
     */
    public final TableField<ZipkinDependenciesRecord, String> CHILD = createField("child", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>cloudins.zipkin_dependencies.call_count</code>.
     */
    public final TableField<ZipkinDependenciesRecord, Long> CALL_COUNT = createField("call_count", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>cloudins.zipkin_dependencies</code> table reference
     */
    public ZipkinDependencies() {
        this("zipkin_dependencies", null);
    }

    /**
     * Create an aliased <code>cloudins.zipkin_dependencies</code> table reference
     */
    public ZipkinDependencies(String alias) {
        this(alias, ZIPKIN_DEPENDENCIES);
    }

    private ZipkinDependencies(String alias, Table<ZipkinDependenciesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ZipkinDependencies(String alias, Table<ZipkinDependenciesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cloudins.CLOUDINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ZipkinDependenciesRecord>> getKeys() {
        return Arrays.<UniqueKey<ZipkinDependenciesRecord>>asList(Keys.KEY_ZIPKIN_DEPENDENCIES_DAY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZipkinDependencies as(String alias) {
        return new ZipkinDependencies(alias, this);
    }

    /**
     * Rename this table
     */
    public ZipkinDependencies rename(String name) {
        return new ZipkinDependencies(name, null);
    }
}
