/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.CloudinsRegion;
import jooq.data.tables.records.CloudinsRegionRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsRegionDao extends DAOImpl<CloudinsRegionRecord, jooq.data.tables.pojos.CloudinsRegion, Long> {

    /**
     * Create a new CloudinsRegionDao without any configuration
     */
    public CloudinsRegionDao() {
        super(CloudinsRegion.CLOUDINS_REGION, jooq.data.tables.pojos.CloudinsRegion.class);
    }

    /**
     * Create a new CloudinsRegionDao with an attached configuration
     */
    public CloudinsRegionDao(Configuration configuration) {
        super(CloudinsRegion.CLOUDINS_REGION, jooq.data.tables.pojos.CloudinsRegion.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.data.tables.pojos.CloudinsRegion object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchById(Long... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.CloudinsRegion fetchOneById(Long value) {
        return fetchOne(CloudinsRegion.CLOUDINS_REGION.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByName(String... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.NAME, values);
    }

    /**
     * Fetch records that have <code>manager_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByManagerId(Long... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.MANAGER_ID, values);
    }

    /**
     * Fetch records that have <code>manager_name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByManagerName(String... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.MANAGER_NAME, values);
    }

    /**
     * Fetch records that have <code>host_ip IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByHostIp(String... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.HOST_IP, values);
    }

    /**
     * Fetch records that have <code>host_username IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByHostUsername(String... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.HOST_USERNAME, values);
    }

    /**
     * Fetch records that have <code>host_password IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByHostPassword(String... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.HOST_PASSWORD, values);
    }

    /**
     * Fetch records that have <code>company IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByCompany(String... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.COMPANY, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsRegion> fetchByRemark(String... values) {
        return fetch(CloudinsRegion.CLOUDINS_REGION.REMARK, values);
    }
}
