/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.CloudinsConfig;
import jooq.data.tables.records.CloudinsConfigRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsConfigDao extends DAOImpl<CloudinsConfigRecord, jooq.data.tables.pojos.CloudinsConfig, Long> {

    /**
     * Create a new CloudinsConfigDao without any configuration
     */
    public CloudinsConfigDao() {
        super(CloudinsConfig.CLOUDINS_CONFIG, jooq.data.tables.pojos.CloudinsConfig.class);
    }

    /**
     * Create a new CloudinsConfigDao with an attached configuration
     */
    public CloudinsConfigDao(Configuration configuration) {
        super(CloudinsConfig.CLOUDINS_CONFIG, jooq.data.tables.pojos.CloudinsConfig.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.data.tables.pojos.CloudinsConfig object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchById(Long... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.CloudinsConfig fetchOneById(Long value) {
        return fetchOne(CloudinsConfig.CLOUDINS_CONFIG.ID, value);
    }

    /**
     * Fetch records that have <code>product IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchByProduct(String... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.PRODUCT, values);
    }

    /**
     * Fetch records that have <code>module IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchByModule(String... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.MODULE, values);
    }

    /**
     * Fetch records that have <code>parm_alias IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchByParmAlias(String... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.PARM_ALIAS, values);
    }

    /**
     * Fetch records that have <code>parm_name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchByParmName(String... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.PARM_NAME, values);
    }

    /**
     * Fetch records that have <code>parm_value IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchByParmValue(String... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.PARM_VALUE, values);
    }

    /**
     * Fetch records that have <code>flag IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchByFlag(Integer... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.FLAG, values);
    }

    /**
     * Fetch records that have <code>comment IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsConfig> fetchByComment(String... values) {
        return fetch(CloudinsConfig.CLOUDINS_CONFIG.COMMENT, values);
    }
}
