/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.CloudinsFieldTable;
import jooq.data.tables.records.CloudinsFieldRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsFieldDao extends DAOImpl<CloudinsFieldRecord, jooq.data.tables.pojos.CloudinsField, Long> {

    /**
     * Create a new CloudinsFieldDao without any configuration
     */
    public CloudinsFieldDao() {
        super(CloudinsFieldTable.CLOUDINS_FIELD, jooq.data.tables.pojos.CloudinsField.class);
    }

    /**
     * Create a new CloudinsFieldDao with an attached configuration
     */
    public CloudinsFieldDao(Configuration configuration) {
        super(CloudinsFieldTable.CLOUDINS_FIELD, jooq.data.tables.pojos.CloudinsField.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.data.tables.pojos.CloudinsField object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchById(Long... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.CloudinsField fetchOneById(Long value) {
        return fetchOne(CloudinsFieldTable.CLOUDINS_FIELD.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByName(String... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.NAME, values);
    }

    /**
     * Fetch records that have <code>manager_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByManagerId(Long... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.MANAGER_ID, values);
    }

    /**
     * Fetch records that have <code>manager_name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByManagerName(String... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.MANAGER_NAME, values);
    }

    /**
     * Fetch records that have <code>host_ip IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByHostIp(String... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.HOST_IP, values);
    }

    /**
     * Fetch records that have <code>host_username IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByHostUsername(String... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.HOST_USERNAME, values);
    }

    /**
     * Fetch records that have <code>host_password IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByHostPassword(String... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.HOST_PASSWORD, values);
    }

    /**
     * Fetch records that have <code>company IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByCompany(String... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.COMPANY, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsField> fetchByRemark(String... values) {
        return fetch(CloudinsFieldTable.CLOUDINS_FIELD.REMARK, values);
    }
}
