/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.CloudinsUser;
import jooq.data.tables.records.CloudinsUserRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudinsUserDao extends DAOImpl<CloudinsUserRecord, jooq.data.tables.pojos.CloudinsUser, Long> {

    /**
     * Create a new CloudinsUserDao without any configuration
     */
    public CloudinsUserDao() {
        super(CloudinsUser.CLOUDINS_USER, jooq.data.tables.pojos.CloudinsUser.class);
    }

    /**
     * Create a new CloudinsUserDao with an attached configuration
     */
    public CloudinsUserDao(Configuration configuration) {
        super(CloudinsUser.CLOUDINS_USER, jooq.data.tables.pojos.CloudinsUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.data.tables.pojos.CloudinsUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchById(Long... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.CloudinsUser fetchOneById(Long value) {
        return fetchOne(CloudinsUser.CLOUDINS_USER.ID, value);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByRoleId(Long... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>region_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByRegionId(Long... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.REGION_ID, values);
    }

    /**
     * Fetch records that have <code>account IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByAccount(String... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.ACCOUNT, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByName(String... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.NAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByPassword(String... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByGender(Boolean... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.GENDER, values);
    }

    /**
     * Fetch records that have <code>mail IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByMail(String... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.MAIL, values);
    }

    /**
     * Fetch records that have <code>company IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByCompany(String... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.COMPANY, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByPhone(Long... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.PHONE, values);
    }

    /**
     * Fetch records that have <code>qq IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByQq(Long... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.QQ, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByStatus(String... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<jooq.data.tables.pojos.CloudinsUser> fetchByRemark(String... values) {
        return fetch(CloudinsUser.CLOUDINS_USER.REMARK, values);
    }
}
