/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.JobSummaryBasic;
import jooq.data.tables.records.JobSummaryBasicRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobSummaryBasicDao extends DAOImpl<JobSummaryBasicRecord, jooq.data.tables.pojos.JobSummaryBasic, Integer> {

    /**
     * Create a new JobSummaryBasicDao without any configuration
     */
    public JobSummaryBasicDao() {
        super(JobSummaryBasic.JOB_SUMMARY_BASIC, jooq.data.tables.pojos.JobSummaryBasic.class);
    }

    /**
     * Create a new JobSummaryBasicDao with an attached configuration
     */
    public JobSummaryBasicDao(Configuration configuration) {
        super(JobSummaryBasic.JOB_SUMMARY_BASIC, jooq.data.tables.pojos.JobSummaryBasic.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(jooq.data.tables.pojos.JobSummaryBasic object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchById(Integer... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.JobSummaryBasic fetchOneById(Integer value) {
        return fetchOne(JobSummaryBasic.JOB_SUMMARY_BASIC.ID, value);
    }

    /**
     * Fetch records that have <code>summary_date IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchBySummaryDate(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.SUMMARY_DATE, values);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByStartTime(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.START_TIME, values);
    }

    /**
     * Fetch records that have <code>last_update_time IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByLastUpdateTime(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.LAST_UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>job_total_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByJobTotalNum(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.JOB_TOTAL_NUM, values);
    }

    /**
     * Fetch records that have <code>job_critical_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByJobCriticalNum(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.JOB_CRITICAL_NUM, values);
    }

    /**
     * Fetch records that have <code>job_severe_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByJobSevereNum(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.JOB_SEVERE_NUM, values);
    }

    /**
     * Fetch records that have <code>job_moderate_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByJobModerateNum(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.JOB_MODERATE_NUM, values);
    }

    /**
     * Fetch records that have <code>job_normal_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByJobNormalNum(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.JOB_NORMAL_NUM, values);
    }

    /**
     * Fetch records that have <code>job_type_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByJobTypeNum(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.JOB_TYPE_NUM, values);
    }

    /**
     * Fetch records that have <code>user_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobSummaryBasic> fetchByUserNum(String... values) {
        return fetch(JobSummaryBasic.JOB_SUMMARY_BASIC.USER_NUM, values);
    }
}
