/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.JobTypeSummary;
import jooq.data.tables.records.JobTypeSummaryRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobTypeSummaryDao extends DAOImpl<JobTypeSummaryRecord, jooq.data.tables.pojos.JobTypeSummary, Integer> {

    /**
     * Create a new JobTypeSummaryDao without any configuration
     */
    public JobTypeSummaryDao() {
        super(JobTypeSummary.JOB_TYPE_SUMMARY, jooq.data.tables.pojos.JobTypeSummary.class);
    }

    /**
     * Create a new JobTypeSummaryDao with an attached configuration
     */
    public JobTypeSummaryDao(Configuration configuration) {
        super(JobTypeSummary.JOB_TYPE_SUMMARY, jooq.data.tables.pojos.JobTypeSummary.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(jooq.data.tables.pojos.JobTypeSummary object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchById(Integer... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.JobTypeSummary fetchOneById(Integer value) {
        return fetchOne(JobTypeSummary.JOB_TYPE_SUMMARY.ID, value);
    }

    /**
     * Fetch records that have <code>job_summary_basic_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobSummaryBasicId(Integer... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_SUMMARY_BASIC_ID, values);
    }

    /**
     * Fetch records that have <code>job_type_name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobTypeName(String... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_TYPE_NAME, values);
    }

    /**
     * Fetch records that have <code>job_type_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobTypeNum(String... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_TYPE_NUM, values);
    }

    /**
     * Fetch records that have <code>job_total_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobTotalNum(String... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_TOTAL_NUM, values);
    }

    /**
     * Fetch records that have <code>job_critical_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobCriticalNum(String... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_CRITICAL_NUM, values);
    }

    /**
     * Fetch records that have <code>job_severe_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobSevereNum(String... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_SEVERE_NUM, values);
    }

    /**
     * Fetch records that have <code>job_moderate_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobModerateNum(String... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_MODERATE_NUM, values);
    }

    /**
     * Fetch records that have <code>job_normal_num IN (values)</code>
     */
    public List<jooq.data.tables.pojos.JobTypeSummary> fetchByJobNormalNum(String... values) {
        return fetch(JobTypeSummary.JOB_TYPE_SUMMARY.JOB_NORMAL_NUM, values);
    }
}
