/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.PlayEvolutions;
import jooq.data.tables.records.PlayEvolutionsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayEvolutionsDao extends DAOImpl<PlayEvolutionsRecord, jooq.data.tables.pojos.PlayEvolutions, Integer> {

    /**
     * Create a new PlayEvolutionsDao without any configuration
     */
    public PlayEvolutionsDao() {
        super(PlayEvolutions.PLAY_EVOLUTIONS, jooq.data.tables.pojos.PlayEvolutions.class);
    }

    /**
     * Create a new PlayEvolutionsDao with an attached configuration
     */
    public PlayEvolutionsDao(Configuration configuration) {
        super(PlayEvolutions.PLAY_EVOLUTIONS, jooq.data.tables.pojos.PlayEvolutions.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(jooq.data.tables.pojos.PlayEvolutions object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.PlayEvolutions> fetchById(Integer... values) {
        return fetch(PlayEvolutions.PLAY_EVOLUTIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.PlayEvolutions fetchOneById(Integer value) {
        return fetchOne(PlayEvolutions.PLAY_EVOLUTIONS.ID, value);
    }

    /**
     * Fetch records that have <code>hash IN (values)</code>
     */
    public List<jooq.data.tables.pojos.PlayEvolutions> fetchByHash(String... values) {
        return fetch(PlayEvolutions.PLAY_EVOLUTIONS.HASH, values);
    }

    /**
     * Fetch records that have <code>applied_at IN (values)</code>
     */
    public List<jooq.data.tables.pojos.PlayEvolutions> fetchByAppliedAt(Timestamp... values) {
        return fetch(PlayEvolutions.PLAY_EVOLUTIONS.APPLIED_AT, values);
    }

    /**
     * Fetch records that have <code>apply_script IN (values)</code>
     */
    public List<jooq.data.tables.pojos.PlayEvolutions> fetchByApplyScript(String... values) {
        return fetch(PlayEvolutions.PLAY_EVOLUTIONS.APPLY_SCRIPT, values);
    }

    /**
     * Fetch records that have <code>revert_script IN (values)</code>
     */
    public List<jooq.data.tables.pojos.PlayEvolutions> fetchByRevertScript(String... values) {
        return fetch(PlayEvolutions.PLAY_EVOLUTIONS.REVERT_SCRIPT, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<jooq.data.tables.pojos.PlayEvolutions> fetchByState(String... values) {
        return fetch(PlayEvolutions.PLAY_EVOLUTIONS.STATE, values);
    }

    /**
     * Fetch records that have <code>last_problem IN (values)</code>
     */
    public List<jooq.data.tables.pojos.PlayEvolutions> fetchByLastProblem(String... values) {
        return fetch(PlayEvolutions.PLAY_EVOLUTIONS.LAST_PROBLEM, values);
    }
}
