/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.SpansBackup;
import jooq.data.tables.records.SpansBackupRecord;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpansBackupDao extends DAOImpl<SpansBackupRecord, jooq.data.tables.pojos.SpansBackup, Record2<Long, Long>> {

    /**
     * Create a new SpansBackupDao without any configuration
     */
    public SpansBackupDao() {
        super(SpansBackup.SPANS_BACKUP, jooq.data.tables.pojos.SpansBackup.class);
    }

    /**
     * Create a new SpansBackupDao with an attached configuration
     */
    public SpansBackupDao(Configuration configuration) {
        super(SpansBackup.SPANS_BACKUP, jooq.data.tables.pojos.SpansBackup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(jooq.data.tables.pojos.SpansBackup object) {
        return compositeKeyRecord(object.getTraceId(), object.getSpanId());
    }

    /**
     * Fetch records that have <code>trace_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByTraceId(Long... values) {
        return fetch(SpansBackup.SPANS_BACKUP.TRACE_ID, values);
    }

    /**
     * Fetch records that have <code>span_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchBySpanId(Long... values) {
        return fetch(SpansBackup.SPANS_BACKUP.SPAN_ID, values);
    }

    /**
     * Fetch records that have <code>endpoint_ipv4 IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByEndpointIpv4(Integer... values) {
        return fetch(SpansBackup.SPANS_BACKUP.ENDPOINT_IPV4, values);
    }

    /**
     * Fetch records that have <code>endpoint_service_name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByEndpointServiceName(String... values) {
        return fetch(SpansBackup.SPANS_BACKUP.ENDPOINT_SERVICE_NAME, values);
    }

    /**
     * Fetch records that have <code>start_ts IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByStartTs(Long... values) {
        return fetch(SpansBackup.SPANS_BACKUP.START_TS, values);
    }

    /**
     * Fetch records that have <code>duration IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByDuration(Long... values) {
        return fetch(SpansBackup.SPANS_BACKUP.DURATION, values);
    }

    /**
     * Fetch records that have <code>record_ts IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByRecordTs(Long... values) {
        return fetch(SpansBackup.SPANS_BACKUP.RECORD_TS, values);
    }

    /**
     * Fetch records that have <code>trace_md5 IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByTraceMd5(String... values) {
        return fetch(SpansBackup.SPANS_BACKUP.TRACE_MD5, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByParentId(Long... values) {
        return fetch(SpansBackup.SPANS_BACKUP.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>parent_ip IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByParentIp(Integer... values) {
        return fetch(SpansBackup.SPANS_BACKUP.PARENT_IP, values);
    }

    /**
     * Fetch records that have <code>parent_endpoint_name IN (values)</code>
     */
    public List<jooq.data.tables.pojos.SpansBackup> fetchByParentEndpointName(String... values) {
        return fetch(SpansBackup.SPANS_BACKUP.PARENT_ENDPOINT_NAME, values);
    }
}
