/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.Traces;
import jooq.data.tables.records.TracesRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TracesDao extends DAOImpl<TracesRecord, jooq.data.tables.pojos.Traces, Long> {

    /**
     * Create a new TracesDao without any configuration
     */
    public TracesDao() {
        super(Traces.TRACES, jooq.data.tables.pojos.Traces.class);
    }

    /**
     * Create a new TracesDao with an attached configuration
     */
    public TracesDao(Configuration configuration) {
        super(Traces.TRACES, jooq.data.tables.pojos.Traces.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.data.tables.pojos.Traces object) {
        return object.getTraceId();
    }

    /**
     * Fetch records that have <code>trace_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.Traces> fetchByTraceId(Long... values) {
        return fetch(Traces.TRACES.TRACE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>trace_id = value</code>
     */
    public jooq.data.tables.pojos.Traces fetchOneByTraceId(Long value) {
        return fetchOne(Traces.TRACES.TRACE_ID, value);
    }

    /**
     * Fetch records that have <code>trace_md5 IN (values)</code>
     */
    public List<jooq.data.tables.pojos.Traces> fetchByTraceMd5(String... values) {
        return fetch(Traces.TRACES.TRACE_MD5, values);
    }

    /**
     * Fetch records that have <code>start_ts IN (values)</code>
     */
    public List<jooq.data.tables.pojos.Traces> fetchByStartTs(Long... values) {
        return fetch(Traces.TRACES.START_TS, values);
    }

    /**
     * Fetch records that have <code>record_ts IN (values)</code>
     */
    public List<jooq.data.tables.pojos.Traces> fetchByRecordTs(Long... values) {
        return fetch(Traces.TRACES.RECORD_TS, values);
    }

    /**
     * Fetch records that have <code>duration IN (values)</code>
     */
    public List<jooq.data.tables.pojos.Traces> fetchByDuration(Long... values) {
        return fetch(Traces.TRACES.DURATION, values);
    }

    /**
     * Fetch records that have <code>end_ts IN (values)</code>
     */
    public List<jooq.data.tables.pojos.Traces> fetchByEndTs(Long... values) {
        return fetch(Traces.TRACES.END_TS, values);
    }

    /**
     * Fetch records that have <code>team_code IN (values)</code>
     */
    public List<jooq.data.tables.pojos.Traces> fetchByTeamCode(Short... values) {
        return fetch(Traces.TRACES.TEAM_CODE, values);
    }
}
