/**
 * This class is generated by jOOQ
 */
package jooq.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.data.tables.YarnAppCheckLog;
import jooq.data.tables.records.YarnAppCheckLogRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YarnAppCheckLogDao extends DAOImpl<YarnAppCheckLogRecord, jooq.data.tables.pojos.YarnAppCheckLog, Long> {

    /**
     * Create a new YarnAppCheckLogDao without any configuration
     */
    public YarnAppCheckLogDao() {
        super(YarnAppCheckLog.YARN_APP_CHECK_LOG, jooq.data.tables.pojos.YarnAppCheckLog.class);
    }

    /**
     * Create a new YarnAppCheckLogDao with an attached configuration
     */
    public YarnAppCheckLogDao(Configuration configuration) {
        super(YarnAppCheckLog.YARN_APP_CHECK_LOG, jooq.data.tables.pojos.YarnAppCheckLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.data.tables.pojos.YarnAppCheckLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.YarnAppCheckLog> fetchById(Long... values) {
        return fetch(YarnAppCheckLog.YARN_APP_CHECK_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.data.tables.pojos.YarnAppCheckLog fetchOneById(Long value) {
        return fetchOne(YarnAppCheckLog.YARN_APP_CHECK_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<jooq.data.tables.pojos.YarnAppCheckLog> fetchByAppId(String... values) {
        return fetch(YarnAppCheckLog.YARN_APP_CHECK_LOG.APP_ID, values);
    }

    /**
     * Fetch records that have <code>message IN (values)</code>
     */
    public List<jooq.data.tables.pojos.YarnAppCheckLog> fetchByMessage(String... values) {
        return fetch(YarnAppCheckLog.YARN_APP_CHECK_LOG.MESSAGE, values);
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<jooq.data.tables.pojos.YarnAppCheckLog> fetchByTime(String... values) {
        return fetch(YarnAppCheckLog.YARN_APP_CHECK_LOG.TIME, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<jooq.data.tables.pojos.YarnAppCheckLog> fetchByType(String... values) {
        return fetch(YarnAppCheckLog.YARN_APP_CHECK_LOG.TYPE, values);
    }

    /**
     * Fetch records that have <code>displayed IN (values)</code>
     */
    public List<jooq.data.tables.pojos.YarnAppCheckLog> fetchByDisplayed(Boolean... values) {
        return fetch(YarnAppCheckLog.YARN_APP_CHECK_LOG.DISPLAYED, values);
    }

    /**
     * Fetch records that have <code>isread IN (values)</code>
     */
    public List<jooq.data.tables.pojos.YarnAppCheckLog> fetchByIsread(Boolean... values) {
        return fetch(YarnAppCheckLog.YARN_APP_CHECK_LOG.ISREAD, values);
    }
}
